all: html

SPHINX_PROJECT_NAME = SOMANET Standalone Profile Velocity Control Demo
VERSION = 1.0
SOURCE_INCLUDE_DIRS = ../../app_demo_bldc_velocity
XDOC_DIR ?= ../../../xdoc
include $(XDOC_DIR)/Makefile.inc
