sc_sncn_motoctrl_sin: module_comm/src/comm.h File Reference
comm.h File Reference
#include <bldc_motor_config.h>
#include <refclk.h>
#include <ctrlproto.h>
#include <qei_client.h>
#include <internal_config.h>
#include <comm_loop_client.h>
Functions
int get_target_torque (ctrl_proto_values_t InOut)
Get target torque from Ethercat.
int get_target_velocity (ctrl_proto_values_t InOut)
Get target velocity from Ethercat.
int get_target_position (ctrl_proto_values_t InOut)
Get target position from Ethercat.
void send_actual_torque (int actual_torque, ctrl_proto_values_t &InOut)
Send actual torque to Ethercat.
void send_actual_velocity (int actual_velocity, ctrl_proto_values_t &InOut)
Send actual velocity to Ethercat.
void send_actual_position (int actual_position, ctrl_proto_values_t &InOut)
Send actual position to Ethercat.
void update_hall_param_ecat (hall_par &hall_params, chanend coe_out)
Update Hall sensor parameters from Ethercat.
void update_qei_param_ecat (qei_par &qei_params, chanend coe_out)
Update QEI sensor parameters from Ethercat.
void update_cst_param_ecat (cst_par &cst_params, chanend coe_out)
Update cyclic synchronous torque parameters from Ethercat.
void update_csv_param_ecat (csv_par &csv_params, chanend coe_out)
Update cyclic synchronous velocity parameters from Ethercat.
void update_csp_param_ecat (csp_par &csp_params, chanend coe_out)
Update cyclic synchronous position parameters from Ethercat.
void update_pt_param_ecat (pt_par &pt_params, chanend coe_out)
Update profile torque parameters from Ethercat.
void update_pv_param_ecat (pv_par &pv_params, chanend coe_out)
Update profile velocity parameters from Ethercat.
void update_pp_param_ecat (pp_par &pp_params, chanend coe_out)
Update profile position parameters from Ethercat.
void update_torque_ctrl_param_ecat (ctrl_par &torque_ctrl_params, chanend coe_out)
Update torque control PID parameters from Ethercat.
void update_velocity_ctrl_param_ecat (ctrl_par &velocity_ctrl_params, chanend coe_out)
Update velocity control PID parameters from Ethercat.
void update_position_ctrl_param_ecat (ctrl_par &position_ctrl_params, chanend coe_out)
Update position control PID params from Ethercat.
void set_commutation_param_ecat (chanend c_signal, hall_par &hall_params, qei_par &qei_params, int nominal_speed)
Set commutation parameters from Ethercat communication loop.
void set_hall_param_ecat (chanend c_hall, hall_par &hall_params)
Set hall sensor parameters from Ethercat communication loop.
void set_qei_param_ecat (chanend c_qei, qei_par &qei_params)
Set QEI sensor parameters from Ethercat communication loop.
void commutation_init_ecat (chanend c_signal, hall_par &hall_params, qei_par &qei_params, commutation_par &commutation_params)
Initialize commutation parameters from Ethercat communication loop (call before start-up of Commutation loop)
void hall_init_ecat (chanend c_hall, hall_par &hall_params)
Initialize hall sensor parameters from Ethercat communication loop (call before start-up of Hall acquisition loop)
void qei_init_ecat (chanend c_qei, qei_par &qei_params)
Initialize QEI sensor parameters from Ethercat communication loop (call before start-up of QEI acquisition loop)
Detailed Description
Ctrlproto data struct client
Copyright (c) 2014, Synapticon GmbH All rights reserved. Author: Pavan Kanajar pkana.nosp@m.jar@.nosp@m.synap.nosp@m.tico.nosp@m.n.com
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Execution of this software or parts of it exclusively takes place on hardware produced by Synapticon GmbH.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
The views and conclusions contained in the software and documentation are those of the authors and should not be interpreted as representing official policies, either expressed or implied, of the Synapticon GmbH.
Definition in file comm.h.
Function Documentation
void commutation_init_ecat (chanend c_signal, hall_par & hall_params, qei_par & qei_params, commutation_par & commutation_params)
Initialize commutation parameters from Ethercat communication loop (call before start-up of Commutation loop)
Output Channel c_signal channel to signal Commutation loop
Input
Parameters
hall_params struct defines the pole-pairs and gear ratio
qei_params struct defines the quadrature encoder (QEI) resolution, sensor type and gear-ratio used for the motor
nominal_speed defines nominal speed for the motor
Definition at line 212 of file comm.xc.
References S_COMMUTATION::angle_variance, CHECK_BUSY, S_COMMUTATION::flag, S_QEI::gear_ratio, S_Hall::gear_ratio, S_QEI::index, INIT_BUSY, init_state(), S_QEI::max_count, S_COMMUTATION::max_speed_reached, S_Hall::pole_pairs, S_COMMUTATION::qei_backward_offset, S_COMMUTATION::qei_forward_offset, S_QEI::real_counts, and SET_COMM_PARAM_ECAT.
Referenced by main().
int get_target_position (ctrl_proto_values_t InOut)
Get target position from Ethercat.
Output
Returns
actual position from torque control in degree * 10000
Definition at line 53 of file comm.xc.
Referenced by ecat_motor_drive().
int get_target_torque (ctrl_proto_values_t InOut)
Get target torque from Ethercat.
Output
Returns
target torque from Ethercat in range [0 - mNm * Current Resolution]
Definition at line 43 of file comm.xc.
Referenced by ecat_motor_drive().
int get_target_velocity (ctrl_proto_values_t InOut)
Get target velocity from Ethercat.
Output
Returns
target velocity from Ethercat in rpm
Definition at line 48 of file comm.xc.
Referenced by ecat_motor_drive().
void hall_init_ecat (chanend c_hall, hall_par & hall_params)
Initialize hall sensor parameters from Ethercat communication loop (call before start-up of Hall acquisition loop)
Output Channel c_hall channel to signal Hall acquisition loop
Input
Parameters
hall_params struct defines the pole-pairs and gear ratio
Definition at line 276 of file comm.xc.
References CHECK_BUSY, S_Hall::gear_ratio, INIT_BUSY, init_state(), S_Hall::pole_pairs, and SET_HALL_PARAM_ECAT.
Referenced by main().
void qei_init_ecat (chanend c_qei, qei_par & qei_params)
Initialize QEI sensor parameters from Ethercat communication loop (call before start-up of QEI acquisition loop)
Output Channel c_qei channel to signal QEI acquisition loop
Input
Parameters
qei_params struct defines the quadrature encoder (QEI) resolution, sensor type and gear-ratio used for the motor
Definition at line 319 of file comm.xc.
References CHECK_BUSY, S_QEI::gear_ratio, S_QEI::index, INIT_BUSY, init_state(), S_QEI::max_count, S_QEI::poles, S_QEI::real_counts, and SET_QEI_PARAM_ECAT.
Referenced by main().
void send_actual_position (int actual_position, ctrl_proto_values_t & InOut)
Send actual position to Ethercat.
Input
Parameters
actual_position sent to Ethercat in degree * 10000
Definition at line 68 of file comm.xc.
Referenced by ecat_motor_drive().
void send_actual_torque (int actual_torque, ctrl_proto_values_t & InOut)
Send actual torque to Ethercat.
Input
Parameters
actual_torque sent to Ethercat in range [0 - mNm * Current Resolution]
Definition at line 58 of file comm.xc.
Referenced by ecat_motor_drive().
void send_actual_velocity (int actual_velocity, ctrl_proto_values_t & InOut)
Send actual velocity to Ethercat.
Input
Parameters
actual_velocity sent to Ethercat in rpm
Definition at line 63 of file comm.xc.
Referenced by ecat_motor_drive().
void set_commutation_param_ecat (chanend c_signal, hall_par & hall_params, qei_par & qei_params, int nominal_speed)
Set commutation parameters from Ethercat communication loop.
Output Channel c_signal channel to signal Commutation loop
Input
Parameters
hall_params struct defines the pole-pairs and gear ratio
qei_params struct defines the quadrature encoder (QEI) resolution, sensor type and gear-ratio used for the motor
nominal_speed defines nominal speed for the motor
Definition at line 200 of file comm.xc.
References S_QEI::gear_ratio, S_Hall::gear_ratio, S_QEI::index, S_QEI::max_count, S_Hall::pole_pairs, S_QEI::real_counts, and SET_COMM_PARAM_ECAT.
Referenced by ecat_motor_drive().
void set_hall_param_ecat (chanend c_hall, hall_par & hall_params)
Set hall sensor parameters from Ethercat communication loop.
Output Channel c_hall channel to signal Hall acquisition loop
Input
Parameters
hall_params struct defines the pole-pairs and gear ratio
Definition at line 269 of file comm.xc.
References S_Hall::gear_ratio, S_Hall::pole_pairs, and SET_HALL_PARAM_ECAT.
Referenced by ecat_motor_drive().
void set_qei_param_ecat (chanend c_qei, qei_par & qei_params)
Set QEI sensor parameters from Ethercat communication loop.
Output Channel c_qei channel to signal QEI acquisition loop
Input
Parameters
qei_params struct defines the quadrature encoder (QEI) resolution, sensor type and gear-ratio used for the motor
Definition at line 308 of file comm.xc.
References S_QEI::gear_ratio, S_QEI::index, S_QEI::max_count, S_QEI::poles, S_QEI::real_counts, and SET_QEI_PARAM_ECAT.
Referenced by ecat_motor_drive().
void update_csp_param_ecat (csp_par & csp_params, chanend coe_out)
Update cyclic synchronous position parameters from Ethercat.
Parameters
csp_params struct defines the cyclic synchronous position params
Definition at line 105 of file comm.xc.
References CYCLIC_SYNCHRONOUS_POSITION_PARAM::base, CYCLIC_SYNCHRONOUS_VELOCITY_PARAM::max_motor_speed, CYCLIC_SYNCHRONOUS_POSITION_PARAM::max_position_limit, CYCLIC_SYNCHRONOUS_VELOCITY_PARAM::nominal_current, and CYCLIC_SYNCHRONOUS_VELOCITY_PARAM::polarity.
Referenced by ecat_motor_drive().
void update_cst_param_ecat (cst_par & cst_params, chanend coe_out)
Update cyclic synchronous torque parameters from Ethercat.
Parameters
cst_params struct defines the cyclic synchronous torque params
Definition at line 84 of file comm.xc.
References CYCLIC_SYNCHRONOUS_TORQUE_PARAM::motor_torque_constant, CYCLIC_SYNCHRONOUS_TORQUE_PARAM::nominal_current, CYCLIC_SYNCHRONOUS_TORQUE_PARAM::nominal_motor_speed, and CYCLIC_SYNCHRONOUS_TORQUE_PARAM::polarity.
Referenced by ecat_motor_drive().
void update_csv_param_ecat (csv_par & csv_params, chanend coe_out)
Update cyclic synchronous velocity parameters from Ethercat.
Parameters
csv_params struct defines the cyclic synchronous velocity params
Definition at line 94 of file comm.xc.
References CYCLIC_SYNCHRONOUS_VELOCITY_PARAM::max_motor_speed, CYCLIC_SYNCHRONOUS_VELOCITY_PARAM::motor_torque_constant, CYCLIC_SYNCHRONOUS_VELOCITY_PARAM::nominal_current, and CYCLIC_SYNCHRONOUS_VELOCITY_PARAM::polarity.
Referenced by ecat_motor_drive().
void update_hall_param_ecat (hall_par & hall_params, chanend coe_out)
Update Hall sensor parameters from Ethercat.
Parameters
hall_params struct defines the pole-pairs and gear ratio
Definition at line 73 of file comm.xc.
References S_Hall::gear_ratio, and S_Hall::pole_pairs.
Referenced by ecat_motor_drive().
void update_position_ctrl_param_ecat (ctrl_par & position_ctrl_params, chanend coe_out)
Update position control PID params from Ethercat.
Parameters
position_ctrl_params struct defines position control PID params
Definition at line 181 of file comm.xc.
References S_Control::Control_limit, S_Control::Integral_limit, S_Control::Kd_d, S_Control::Kd_n, S_Control::Ki_d, S_Control::Ki_n, S_Control::Kp_d, S_Control::Kp_n, S_Control::Loop_time, and MSEC_STD.
Referenced by ecat_motor_drive().
void update_pp_param_ecat (pp_par & pp_params, chanend coe_out)
Update profile position parameters from Ethercat.
Parameters
pp_params struct defines the profile position params
Definition at line 133 of file comm.xc.
References PROFILE_POSITION_PARAM::base, PROFILE_VELOCITY_PARAM::max_profile_velocity, PROFILE_VELOCITY_PARAM::profile_deceleration, and PROFILE_POSITION_PARAM::profile_velocity.
Referenced by ecat_motor_drive().
void update_pt_param_ecat (pt_par & pt_params, chanend coe_out)
Update profile torque parameters from Ethercat.
Parameters
pt_params struct defines the profile torque params
Definition at line 116 of file comm.xc.
References PROFILE_TORQUE_PARAM::polarity, and PROFILE_TORQUE_PARAM::profile_slope.
Referenced by ecat_motor_drive().
void update_pv_param_ecat (pv_par & pv_params, chanend coe_out)
Update profile velocity parameters from Ethercat.
Parameters
pv_params struct defines the profile velocity params
Definition at line 125 of file comm.xc.
References PROFILE_VELOCITY_PARAM::max_profile_velocity, and PROFILE_VELOCITY_PARAM::profile_acceleration.
Referenced by ecat_motor_drive().
void update_qei_param_ecat (qei_par & qei_params, chanend coe_out)
Update QEI sensor parameters from Ethercat.
Parameters
qei_params struct defines the quadrature encoder (QEI) resolution, sensor type and gear-ratio used for the motor
Definition at line 78 of file comm.xc.
References __qei_max_counts(), S_QEI::gear_ratio, S_QEI::index, S_QEI::max_count, and S_QEI::real_counts.
Referenced by ecat_motor_drive().
void update_torque_ctrl_param_ecat (ctrl_par & torque_ctrl_params, chanend coe_out)
Update torque control PID parameters from Ethercat.
Parameters
torque_ctrl_params struct defines torque control PID params
Definition at line 144 of file comm.xc.
References S_Control::Control_limit, S_Control::Integral_limit, S_Control::Kd_d, S_Control::Kd_n, S_Control::Ki_d, S_Control::Ki_n, S_Control::Kp_d, S_Control::Kp_n, S_Control::Loop_time, and MSEC_STD.
Referenced by ecat_motor_drive().
void update_velocity_ctrl_param_ecat (ctrl_par & velocity_ctrl_params, chanend coe_out)
Update velocity control PID parameters from Ethercat.
Parameters
velocity_ctrl_params struct defines velocity control PID params
Definition at line 163 of file comm.xc.
References S_Control::Control_limit, S_Control::Integral_limit, S_Control::Kd_d, S_Control::Kd_n, S_Control::Ki_d, S_Control::Ki_n, S_Control::Kp_d, S_Control::Kp_n, S_Control::Loop_time, and MSEC_STD.
Referenced by ecat_motor_drive().