sc_sncn_motoctrl_sin: module_commutation/commutation/comm_loop_server.xc File Reference
comm_loop_server.xc File Reference
#include "comm_loop_server.h"
#include <xs1.h>
#include <stdint.h>
#include <pwm_config.h>
#include "pwm_cli_inv.h"
#include "predriver/a4935.h"
#include "sine_table_big.h"
#include "adc_client_ad7949.h"
#include "hall_client.h"
#include <xscope.h>
#include "refclk.h"
#include "qei_client.h"
#include <internal_config.h>
#include "print.h"
Macros
#define FORWARD_CONSTANT 683
#define REVERSE_CONSTANT 2731
Functions
void commutation_init_to_zero (chanend c_pwm_ctrl)
int absolute (int var)
void commutation_client_hanlder (chanend c_commutation, int command, commutation_par &commutation_params, int &voltage, int &sensor_select, int init_state)
void commutation_sinusoidal_loop (int sensor_select, hall_par &hall_params, qei_par &qei_params, commutation_par &commutation_params, chanend c_hall, chanend c_qei, chanend c_pwm_ctrl, chanend c_signal, chanend c_commutation_p1, chanend c_commutation_p2, chanend c_commutation_p3)
void commutation_sinusoidal (chanend c_hall, chanend c_qei, chanend c_signal, chanend c_watchdog, chanend c_commutation_p1, chanend c_commutation_p2, chanend c_commutation_p3, chanend c_pwm_ctrl, hall_par &hall_params, qei_par &qei_params, commutation_par &commutation_params)
Sinusoidal based Commutation Loop.
Detailed Description
Commutation Loop based on sinusoidal commutation method
Copyright (c) 2014, Synapticon GmbH All rights reserved. Author: Ludwig Orgler lorgl.nosp@m.er@s.nosp@m.ynapt.nosp@m.icon.nosp@m..com, Pavan Kanajar pkana.nosp@m.jar@.nosp@m.synap.nosp@m.tico.nosp@m.n.com & Martin Schwarz mschw.nosp@m.arz@.nosp@m.synap.nosp@m.tico.nosp@m.n.com
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Execution of this software or parts of it exclusively takes place on hardware produced by Synapticon GmbH.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
The views and conclusions contained in the software and documentation are those of the authors and should not be interpreted as representing official policies, either expressed or implied, of the Synapticon GmbH.
Definition in file comm_loop_server.xc.
Macro Definition Documentation
#define FORWARD_CONSTANT 683
Definition at line 57 of file comm_loop_server.xc.
Referenced by commutation_sinusoidal_loop().
#define REVERSE_CONSTANT 2731
Definition at line 58 of file comm_loop_server.xc.
Referenced by commutation_sinusoidal_loop().
Function Documentation
int absolute (int var)
Definition at line 72 of file comm_loop_server.xc.
Referenced by commutation_sinusoidal_loop().
void commutation_client_hanlder (chanend c_commutation, int command, commutation_par & commutation_params, int & voltage, int & sensor_select, int init_state)
Definition at line 83 of file comm_loop_server.xc.
References S_COMMUTATION::angle_variance, CHECK_BUSY, DISABLE_FETS, ENABLE_FETS, init_state(), S_COMMUTATION::max_speed_reached, S_COMMUTATION::offset_backward, S_COMMUTATION::offset_forward, SENSOR_SELECT, SET_COMMUTATION_PARAMS, and SET_VOLTAGE.
Referenced by commutation_sinusoidal_loop().
void commutation_init_to_zero (chanend c_pwm_ctrl)
Definition at line 64 of file comm_loop_server.xc.
Referenced by commutation_sinusoidal().
void commutation_sinusoidal (chanend c_hall, chanend c_qei, chanend c_signal, chanend c_watchdog, chanend c_commutation_p1, chanend c_commutation_p2, chanend c_commutation_p3, chanend c_pwm_ctrl, hall_par & hall_params, qei_par & qei_params, commutation_par & commutation_params)
Sinusoidal based Commutation Loop.
Input Channels c_hall channel to receive position information from hall sensor c_qei channel to receive position information from qei sensor c_signal channel for signaling after initialization of commutation loop c_commutation_p1 channel to receive motor voltage input value - priority 1 (highest) 1 ... (lowest) 3 c_commutation_p2 channel to receive motor voltage input value - priority 2 c_commutation_p3 channel to receive motor voltage input value - priority 3 c_watchdog channel to start the watchdog
Output Channels c_pwm_ctrl channel to set pwm level output to motor phases
Input
Parameters
hall_params struct defines the pole-pairs and gear ratio
qei_params the struct defines sensor type and resolution parameters for qei
commutation_params struct defines the commutation angle parameters
Definition at line 295 of file comm_loop_server.xc.
References A4935_BIT_PWMH, A4935_BIT_PWML, a4935_init(), commutation_init_to_zero(), commutation_sinusoidal_loop(), HALL, INIT_BUSY, init_state(), SEC_FAST, USEC_FAST, and WD_CMD_START.
Referenced by main().
void commutation_sinusoidal_loop (int sensor_select, hall_par & hall_params, qei_par & qei_params, commutation_par & commutation_params, chanend c_hall, chanend c_qei, chanend c_pwm_ctrl, chanend c_signal, chanend c_commutation_p1, chanend c_commutation_p2, chanend c_commutation_p3)
Definition at line 120 of file comm_loop_server.xc.
References absolute(), S_COMMUTATION::angle_variance, CHECK_BUSY, commutation_client_hanlder(), S_COMMUTATION::flag, FORWARD_CONSTANT, S_QEI::gear_ratio, S_Hall::gear_ratio, get_hall_position(), get_hall_velocity(), HALL, S_QEI::index, INIT, init_qei_velocity_params(), init_state(), S_QEI::max_count, S_COMMUTATION::max_speed_reached, S_COMMUTATION::offset_backward, S_COMMUTATION::offset_forward, S_Hall::pole_pairs, PWM_MAX_VALUE, PWM_MIN_LIMIT, QEI, S_COMMUTATION::qei_backward_offset, S_COMMUTATION::qei_forward_offset, S_QEI::real_counts, REVERSE_CONSTANT, SET_COMM_PARAM_ECAT, and sine_third_expanded().
Referenced by commutation_sinusoidal().