sc_sncn_motoctrl_sin: module_commutation/commutation/comm_loop_client.xc File Reference
comm_loop_client.xc File Reference
#include "comm_loop_client.h"
#include <xs1.h>
#include <stdint.h>
#include <bldc_motor_config.h>
#include "refclk.h"
#include <internal_config.h>
#include "print.h"
Functions
void init_commutation_param (commutation_par &commutation_params, hall_par &hall_params, int nominal_speed)
Initialize commutation parameters.
void commutation_sensor_select (chanend c_commutation, int sensor_select)
Specify sensor for motor commutation.
void set_commutation_params (chanend c_commutation, commutation_par &commutation_params)
Internal function used to set the commutation parameters.
void set_commutation_sinusoidal (chanend c_commutation, int input_voltage)
Set Input voltage for commutation loop.
Detailed Description
Commutation Loop Client functions Author: Pavan Kanajar pkana.nosp@m.jar@.nosp@m.synap.nosp@m.tico.nosp@m.n.com, Ludwig Orgler lorgl.nosp@m.er@s.nosp@m.ynapt.nosp@m.icon.nosp@m..com & Martin Schwarz mschw.nosp@m.arz@.nosp@m.synap.nosp@m.tico.nosp@m.n.com
Definition in file comm_loop_client.xc.
Function Documentation
void commutation_sensor_select (chanend c_commutation, int sensor_select)
Specify sensor for motor commutation.
c_commutation channel to send information to the commutation loop
Input
Parameters
sensor_select specify sensor used for commutation through defines HALL and QEI
Definition at line 69 of file comm_loop_client.xc.
References SENSOR_SELECT.
void init_commutation_param (commutation_par & commutation_params, hall_par & hall_params, int nominal_speed)
Initialize commutation parameters.
Parameters
commutation_params struct defines the commutation angle parameters
hall_params struct defines the pole-pairs and gear ratio
nominal speed is the rated speed for the motor given on specs sheet
Definition at line 51 of file comm_loop_client.xc.
References S_COMMUTATION::angle_variance, S_COMMUTATION::flag, S_COMMUTATION::max_speed_reached, S_Hall::pole_pairs, S_COMMUTATION::qei_backward_offset, and S_COMMUTATION::qei_forward_offset.
Referenced by main().
void set_commutation_params (chanend c_commutation, commutation_par & commutation_params)
Internal function used to set the commutation parameters.
Output Channels c_commutation channel to send out motor voltage input value
Input
Parameters
commutation_params struct defines the commutation angle parameters
Definition at line 76 of file comm_loop_client.xc.
References S_COMMUTATION::angle_variance, S_COMMUTATION::max_speed_reached, S_COMMUTATION::offset_backward, S_COMMUTATION::offset_forward, and SET_COMMUTATION_PARAMS.
void set_commutation_sinusoidal (chanend c_commutation, int input_voltage)
Set Input voltage for commutation loop.
Output Channels c_commutation channel to send out motor voltage input value
Input
Parameters
input_voltage is motor voltage input value to be set (range allowed -13739 to 13739)
Definition at line 86 of file comm_loop_client.xc.
Referenced by _torque_ctrl(), position_control(), and velocity_control().