sc_sncn_motoctrl_sin: module_commutation/commutation/comm_loop_server.h File Reference
comm_loop_server.h File Reference
#include <bldc_motor_config.h>
#include "comm_loop_client.h"
#include <watchdog.h>
Functions
void commutation_sinusoidal (chanend c_hall, chanend c_qei, chanend c_signal, chanend c_watchdog, chanend c_commutation_p1, chanend c_commutation_p2, chanend c_commutation_p3, chanend c_pwm_ctrl, hall_par &hall_params, qei_par &qei_params, commutation_par &commutation_params)
Sinusoidal based Commutation Loop.
Detailed Description
Commutation Loop based on sinusoidal commutation method Author: Ludwig Orgler lorgl.nosp@m.er@s.nosp@m.ynapt.nosp@m.icon.nosp@m..com, Pavan Kanajar pkana.nosp@m.jar@.nosp@m.synap.nosp@m.tico.nosp@m.n.com & Martin Schwarz mschw.nosp@m.arz@.nosp@m.synap.nosp@m.tico.nosp@m.n.com
Definition in file comm_loop_server.h.
Function Documentation
void commutation_sinusoidal (chanend c_hall, chanend c_qei, chanend c_signal, chanend c_watchdog, chanend c_commutation_p1, chanend c_commutation_p2, chanend c_commutation_p3, chanend c_pwm_ctrl, hall_par & hall_params, qei_par & qei_params, commutation_par & commutation_params)
Sinusoidal based Commutation Loop.
Input Channels c_hall channel to receive position information from hall sensor c_qei channel to receive position information from qei sensor c_signal channel for signaling after initialization of commutation loop c_commutation_p1 channel to receive motor voltage input value - priority 1 (highest) 1 ... (lowest) 3 c_commutation_p2 channel to receive motor voltage input value - priority 2 c_commutation_p3 channel to receive motor voltage input value - priority 3 c_watchdog channel to start the watchdog
Output Channels c_pwm_ctrl channel to set pwm level output to motor phases
Input
Parameters
hall_params struct defines the pole-pairs and gear ratio
qei_params the struct defines sensor type and resolution parameters for qei
commutation_params struct defines the commutation angle parameters
Definition at line 295 of file comm_loop_server.xc.
References A4935_BIT_PWMH, A4935_BIT_PWML, a4935_init(), commutation_init_to_zero(), commutation_sinusoidal_loop(), HALL, INIT_BUSY, init_state(), SEC_FAST, USEC_FAST, and WD_CMD_START.
Referenced by main().