sc_sncn_motoctrl_sin: module_commutation/commutation/comm_loop_client.h File Reference
comm_loop_client.h File Reference
#include <pwm_config.h>
#include "pwm_cli_inv.h"
#include "predriver/a4935.h"
#include "sine_table_big.h"
#include "adc_client_ad7949.h"
#include "hall_client.h"
#include <bldc_motor_config.h>
Data Structures
struct S_COMMUTATION
Struct for commutation parameters.
Typedefs
typedef struct S_COMMUTATION commutation_par
Struct for commutation parameters.
Functions
void init_commutation_param (commutation_par &commutation_params, hall_par &hall_params, int nominal_speed)
Initialize commutation parameters.
int init_commutation (chanend c_signal)
Initialize commutation loop.
void commutation_sensor_select (chanend c_commutation, int sensor_select)
Specify sensor for motor commutation.
void set_commutation_sinusoidal (chanend c_commutation, int input_voltage)
Set Input voltage for commutation loop.
void set_commutation_params (chanend c_commutation, commutation_par &commutation_params)
Internal function used to set the commutation parameters.
Detailed Description
Commutation Loop Client functions
Copyright (c) 2014, Synapticon GmbH All rights reserved. Author: Pavan Kanajar pkana.nosp@m.jar@.nosp@m.synap.nosp@m.tico.nosp@m.n.com, Ludwig Orgler lorgl.nosp@m.er@s.nosp@m.ynapt.nosp@m.icon.nosp@m..com & Martin Schwarz mschw.nosp@m.arz@.nosp@m.synap.nosp@m.tico.nosp@m.n.com
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Execution of this software or parts of it exclusively takes place on hardware produced by Synapticon GmbH.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
The views and conclusions contained in the software and documentation are those of the authors and should not be interpreted as representing official policies, either expressed or implied, of the Synapticon GmbH.
Definition in file comm_loop_client.h.
Typedef Documentation
typedef struct S_COMMUTATION commutation_par
Struct for commutation parameters.
Function Documentation
void commutation_sensor_select (chanend c_commutation, int sensor_select)
Specify sensor for motor commutation.
c_commutation channel to send information to the commutation loop
Input
Parameters
sensor_select specify sensor used for commutation through defines HALL and QEI
Definition at line 69 of file comm_loop_client.xc.
References SENSOR_SELECT.
int init_commutation (chanend c_signal)
Initialize commutation loop.
void init_commutation_param (commutation_par & commutation_params, hall_par & hall_params, int nominal_speed)
Initialize commutation parameters.
Parameters
commutation_params struct defines the commutation angle parameters
hall_params struct defines the pole-pairs and gear ratio
nominal speed is the rated speed for the motor given on specs sheet
Definition at line 51 of file comm_loop_client.xc.
References S_COMMUTATION::angle_variance, S_COMMUTATION::flag, S_COMMUTATION::max_speed_reached, S_Hall::pole_pairs, S_COMMUTATION::qei_backward_offset, and S_COMMUTATION::qei_forward_offset.
Referenced by main().
void set_commutation_params (chanend c_commutation, commutation_par & commutation_params)
Internal function used to set the commutation parameters.
Output Channels c_commutation channel to send out motor voltage input value
Input
Parameters
commutation_params struct defines the commutation angle parameters
Definition at line 76 of file comm_loop_client.xc.
References S_COMMUTATION::angle_variance, S_COMMUTATION::max_speed_reached, S_COMMUTATION::offset_backward, S_COMMUTATION::offset_forward, and SET_COMMUTATION_PARAMS.
void set_commutation_sinusoidal (chanend c_commutation, int input_voltage)
Set Input voltage for commutation loop.
Output Channels c_commutation channel to send out motor voltage input value
Input
Parameters
input_voltage is motor voltage input value to be set (range allowed -13739 to 13739)
Definition at line 86 of file comm_loop_client.xc.
Referenced by _torque_ctrl(), position_control(), and velocity_control().