sc_sncn_motoctrl_sin: module_common/src/delay.xc File Reference
delay.xc File Reference
#include <refclk.h>
Functions
void wait_ms (int milliseconds, int core_id, timer t)
Delay function in milliseconds.
void wait_s (int seconds, int core_id, timer t)
Delay function in seconds Max delay of 21 seconds on Core: 0,1,2 and 8 seconds on Core: 3.
Detailed Description
Author
: Martin Schwarz mschw.nosp@m.arz@.nosp@m.synap.nosp@m.tico.nosp@m.n.com, Pavan Kanajar pkana.nosp@m.jar@.nosp@m.synap.nosp@m.tico.nosp@m.n.com
Definition in file delay.xc.
Function Documentation
void wait_ms (int milliseconds, int core_id, timer t)
Delay function in milliseconds.
Parameters
milliseconds specify the delay in milliseconds
core_id specify the core number in which the function is called
t timer used to calculate the milliseconds elapsed
Definition at line 43 of file delay.xc.
References MSEC_FAST, and MSEC_STD.
Referenced by external_pot_test(), hall_test(), and qei_test().
void wait_s (int seconds, int core_id, timer t)
Delay function in seconds Max delay of 21 seconds on Core: 0,1,2 and 8 seconds on Core: 3.
Parameters
seconds specify the delay in seconds
core_id specify the core number in which the function is called
t timer used to calculate the seconds elapsed
Definition at line 58 of file delay.xc.
References SEC_FAST, and SEC_STD.