sc_sncn_motoctrl_sin: module_sm/src/drive_config.h File Reference
drive_config.h File Reference
Data Structures
struct S_Check_list
Macros
#define PP 1 /* Profile Position mode O*/
Modes of Operation (CiA402 Standard)
#define VL 2 /* Velocity mode (frequency converter) O*/
#define PV 3 /* Profile velocity mode O*/
#define TQ 4 /* Torque profile mode O*/
#define HM 6 /* Homing mode O*/
#define IP 7 /* Interpolated position mode O*/
#define CSP 8 /* Cyclic synchronous position mode C*/
#define CSV 9 /* Cyclic synchronous velocity mode C*/
#define CST 10 /* Cyclic synchronous torque mode C*/
#define CSTCA 11 /* Cyclic synchronous torque mode with commutation angle O*/
#define SHUTDOWN 0x0006
#define SWITCH_ON 0x000F
#define QUICK_STOP 0x000B
#define CLEAR_FAULT 0x0080
#define START_HOMING 0x001F
#define HALT_HOMING 0x011F
#define ABSOLUTE_POSITIONING 0x001F
#define RELATIVE_POSITIONING 0x005F
#define STOP_POSITIONING 0x010F
#define HALT_PROFILE_VELOCITY 0x010F
#define TARGET_REACHED 0x0400
#define HOMING_ATTAINED 0x1000
#define SET_POSITION_ACK 0x1000
#define TARGET_VELOCITY_REACHED 0x0400
#define SWITCH_ON_CONTROL 0x1
#define ENABLE_VOLTAGE_CONTROL 0x2
#define QUICK_STOP_CONTROL 0x4
#define ENABLE_OPERATION_CONTROL 0x8
#define OPERATION_MODES_SPECIFIC_CONTROL 0x70 /*3 bits*/
#define FAULT_RESET_CONTROL 0x80
#define HALT_CONTROL 0x100
#define OPERATION_MODE_SPECIFIC_CONTROL 0x200
#define RESERVED_CONTROL 0x400
#define MANUFACTURER_SPECIFIC_CONTROL 0xf800
#define READY_TO_SWITCH_ON_STATE 0X1
#define SWITCHED_ON_STATE 0X2
#define OPERATION_ENABLED_STATE 0X4
#define FAULT_STATE 0X8
#define VOLTAGE_ENABLED_STATE 0X10
#define QUICK_STOP_STATE 0X20
#define SWITCH_ON_DISABLED_STATE 0X40
#define WARNING_STATE 0X80
#define MANUFACTURER_SPECIFIC_STATE 0X100
#define REMOTE_STATE 0X200
#define TARGET_REACHED_OR_RESERVED_STATE 0X400
#define INTERNAL_LIMIT_ACTIVE_STATE 0X800
#define OPERATION_MODE_SPECIFIC_STATE 0X1000
#define MANUFACTURER_SPECIFIC_STATES 0XC000
Typedefs
typedef int bool
typedef struct S_Check_list check_list
Enumerations
enum { false, true }
Functions
bool __check_commutation_init (chanend c_signal)
Check commutation initialization.
bool __check_hall_init (chanend c_hall)
Check hall initialization.
bool __check_qei_init (chanend c_qei)
Check qei initialization.
bool __check_adc_init ()
Check adc initialization.
bool __check_torque_init (chanend c_torque_ctrl)
Check torque control initialization.
bool __check_velocity_init (chanend c_velocity_ctrl)
Check velocity control initialization.
bool __check_position_init (chanend c_position_ctrl)
Check position control initialization.
int init_state (void)
check_list init_checklist (void)
Initialize checklist params.
void update_checklist (check_list &check_list_param, int mode, chanend c_commutation, chanend c_hall, chanend c_qei, chanend c_adc, chanend c_torque_ctrl, chanend c_velocity_ctrl, chanend c_position_ctrl)
Update Checklist.
int update_statusword (int current_status, int state_reached, int ack, int q_active, int shutdown_ack)
int get_next_state (int in_state, check_list &checklist, int controlword)
int read_controlword_switch_on (int control_word)
int read_controlword_quick_stop (int control_word)
int read_controlword_enable_op (int control_word)
int read_controlword_fault_reset (int control_word)
Detailed Description
Motor Drive defines and configurations
Copyright (c) 2014, Synapticon GmbH All rights reserved. Author: Pavan Kanajar pkana.nosp@m.jar@.nosp@m.synap.nosp@m.tico.nosp@m.n.com
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Execution of this software or parts of it exclusively takes place on hardware produced by Synapticon GmbH.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
The views and conclusions contained in the software and documentation are those of the authors and should not be interpreted as representing official policies, either expressed or implied, of the Synapticon GmbH.
Definition in file drive_config.h.
Macro Definition Documentation
#define ABSOLUTE_POSITIONING 0x001F
Definition at line 79 of file drive_config.h.
#define CLEAR_FAULT 0x0080
Definition at line 70 of file drive_config.h.
#define CSP 8 /* Cyclic synchronous position mode C*/
Definition at line 56 of file drive_config.h.
Referenced by ecat_motor_drive().
#define CST 10 /* Cyclic synchronous torque mode C*/
Definition at line 58 of file drive_config.h.
Referenced by ecat_motor_drive().
#define CSTCA 11 /* Cyclic synchronous torque mode with commutation angle O*/
Definition at line 59 of file drive_config.h.
#define CSV 9 /* Cyclic synchronous velocity mode C*/
Definition at line 57 of file drive_config.h.
Referenced by ecat_motor_drive().
#define ENABLE_OPERATION_CONTROL 0x8
Definition at line 104 of file drive_config.h.
Referenced by read_controlword_enable_op().
#define ENABLE_VOLTAGE_CONTROL 0x2
Definition at line 102 of file drive_config.h.
#define FAULT_RESET_CONTROL 0x80
Definition at line 106 of file drive_config.h.
Referenced by read_controlword_fault_reset().
#define FAULT_STATE 0X8
Definition at line 116 of file drive_config.h.
Referenced by update_statusword().
#define HALT_CONTROL 0x100
Definition at line 107 of file drive_config.h.
#define HALT_HOMING 0x011F
Definition at line 76 of file drive_config.h.
#define HALT_PROFILE_VELOCITY 0x010F
Definition at line 84 of file drive_config.h.
#define HM 6 /* Homing mode O*/
Definition at line 54 of file drive_config.h.
#define HOMING_ATTAINED 0x1000
Definition at line 92 of file drive_config.h.
#define INTERNAL_LIMIT_ACTIVE_STATE 0X800
Definition at line 124 of file drive_config.h.
#define IP 7 /* Interpolated position mode O*/
Definition at line 55 of file drive_config.h.
#define MANUFACTURER_SPECIFIC_CONTROL 0xf800
Definition at line 110 of file drive_config.h.
#define MANUFACTURER_SPECIFIC_STATE 0X100
Definition at line 121 of file drive_config.h.
#define MANUFACTURER_SPECIFIC_STATES 0XC000
Definition at line 126 of file drive_config.h.
#define OPERATION_ENABLED_STATE 0X4
Definition at line 115 of file drive_config.h.
Referenced by update_statusword().
#define OPERATION_MODE_SPECIFIC_CONTROL 0x200
Definition at line 108 of file drive_config.h.
#define OPERATION_MODE_SPECIFIC_STATE 0X1000
Definition at line 125 of file drive_config.h.
#define OPERATION_MODES_SPECIFIC_CONTROL 0x70 /*3 bits*/
Definition at line 105 of file drive_config.h.
#define PP 1 /* Profile Position mode O*/
Modes of Operation (CiA402 Standard)
M - Mandatory, C - Conditional, R - Recommended, O - optional , FG - Function Group
Definition at line 50 of file drive_config.h.
Referenced by ecat_motor_drive().
#define PV 3 /* Profile velocity mode O*/
Definition at line 52 of file drive_config.h.
Referenced by ecat_motor_drive().
#define QUICK_STOP 0x000B
Definition at line 69 of file drive_config.h.
#define QUICK_STOP_CONTROL 0x4
Definition at line 103 of file drive_config.h.
Referenced by read_controlword_quick_stop().
#define QUICK_STOP_STATE 0X20
Definition at line 118 of file drive_config.h.
Referenced by update_statusword().
#define READY_TO_SWITCH_ON_STATE 0X1
Definition at line 113 of file drive_config.h.
Referenced by update_statusword().
#define RELATIVE_POSITIONING 0x005F
Definition at line 80 of file drive_config.h.
#define REMOTE_STATE 0X200
Definition at line 122 of file drive_config.h.
#define RESERVED_CONTROL 0x400
Definition at line 109 of file drive_config.h.
#define SET_POSITION_ACK 0x1000
Definition at line 95 of file drive_config.h.
#define SHUTDOWN 0x0006
Definition at line 67 of file drive_config.h.
#define START_HOMING 0x001F
Definition at line 75 of file drive_config.h.
#define STOP_POSITIONING 0x010F
Definition at line 81 of file drive_config.h.
#define SWITCH_ON 0x000F
Definition at line 68 of file drive_config.h.
#define SWITCH_ON_CONTROL 0x1
Definition at line 101 of file drive_config.h.
Referenced by read_controlword_switch_on().
#define SWITCH_ON_DISABLED_STATE 0X40
Definition at line 119 of file drive_config.h.
Referenced by update_statusword().
#define SWITCHED_ON_STATE 0X2
Definition at line 114 of file drive_config.h.
Referenced by update_statusword().
#define TARGET_REACHED 0x0400
Definition at line 89 of file drive_config.h.
Referenced by update_statusword().
#define TARGET_REACHED_OR_RESERVED_STATE 0X400
Definition at line 123 of file drive_config.h.
#define TARGET_VELOCITY_REACHED 0x0400
Definition at line 98 of file drive_config.h.
#define TQ 4 /* Torque profile mode O*/
Definition at line 53 of file drive_config.h.
Referenced by ecat_motor_drive().
#define VL 2 /* Velocity mode (frequency converter) O*/
Definition at line 51 of file drive_config.h.
#define VOLTAGE_ENABLED_STATE 0X10
Definition at line 117 of file drive_config.h.
Referenced by update_statusword().
#define WARNING_STATE 0X80
Definition at line 120 of file drive_config.h.
Typedef Documentation
typedef int bool
Definition at line 128 of file drive_config.h.
typedef struct S_Check_list check_list
Enumeration Type Documentation
anonymous enum
Enumerator
false
true
Definition at line 129 of file drive_config.h.
Function Documentation
bool __check_adc_init ()
Check adc initialization.
Output
Returns
init state of the adc loop
Definition at line 85 of file drive_sys.xc.
Referenced by update_checklist().
bool __check_commutation_init (chanend c_signal)
Check commutation initialization.
Output
Returns
init state of the commutation loop
Definition at line 61 of file drive_sys.xc.
References CHECK_BUSY, and init_state().
Referenced by _torque_ctrl(), position_control(), update_checklist(), and velocity_control().
bool __check_hall_init (chanend c_hall)
Check hall initialization.
Output
Returns
init state of the hall loop
Definition at line 69 of file drive_sys.xc.
References CHECK_BUSY, and init_state().
Referenced by update_checklist().
bool __check_position_init (chanend c_position_ctrl)
Check position control initialization.
Output
Returns
init state of the position control loop
Definition at line 104 of file drive_sys.xc.
References CHECK_BUSY, and init_state().
Referenced by set_profile_position(), and update_checklist().
bool __check_qei_init (chanend c_qei)
Check qei initialization.
Output
Returns
init state of the qei loop
Definition at line 77 of file drive_sys.xc.
References CHECK_BUSY, and init_state().
Referenced by update_checklist().
bool __check_torque_init (chanend c_torque_ctrl)
Check torque control initialization.
Output
Returns
init state of the torque control loop
Definition at line 90 of file drive_sys.xc.
References CHECK_BUSY, and init_state().
Referenced by set_profile_torque(), and update_checklist().
bool __check_velocity_init (chanend c_velocity_ctrl)
Check velocity control initialization.
Output
Returns
init state of the velocity control loop
Definition at line 97 of file drive_sys.xc.
References CHECK_BUSY, and init_state().
Referenced by set_profile_velocity(), and update_checklist().
int get_next_state (int in_state, check_list & checklist, int controlword)
Definition at line 244 of file drive_sys.xc.
References S_Check_list::fault, read_controlword_enable_op(), read_controlword_fault_reset(), read_controlword_quick_stop(), read_controlword_switch_on(), S_Check_list::ready, and S_Check_list::switch_on.
Referenced by ecat_motor_drive().
check_list init_checklist (void)
Initialize checklist params.
Output
Returns
check_list initialised checklist parameters
Definition at line 112 of file drive_sys.xc.
References S_Check_list::_adc_init, S_Check_list::_commutation_init, S_Check_list::_hall_init, S_Check_list::_position_init, S_Check_list::_qei_init, S_Check_list::_torque_init, S_Check_list::_velocity_init, S_Check_list::fault, INIT_BUSY, S_Check_list::mode_op, S_Check_list::operation_enable, S_Check_list::ready, and S_Check_list::switch_on.
Referenced by ecat_motor_drive().
int init_state (void)
Definition at line 187 of file drive_sys.xc.
Referenced by __check_commutation_init(), __check_hall_init(), __check_position_init(), __check_qei_init(), __check_torque_init(), __check_velocity_init(), _torque_ctrl(), commutation_client_hanlder(), commutation_init_ecat(), commutation_sinusoidal(), commutation_sinusoidal_loop(), ecat_motor_drive(), hall_client_handler(), hall_init_ecat(), position_control(), qei_client_hanlder(), qei_init_ecat(), run_hall(), run_qei(), send_torque_init_state(), set_profile_position(), set_profile_torque(), set_profile_velocity(), and velocity_control().
int read_controlword_enable_op (int control_word)
Definition at line 53 of file drive_sys.xc.
References ENABLE_OPERATION_CONTROL.
Referenced by get_next_state().
int read_controlword_fault_reset (int control_word)
Definition at line 57 of file drive_sys.xc.
References FAULT_RESET_CONTROL.
Referenced by get_next_state().
int read_controlword_quick_stop (int control_word)
Definition at line 49 of file drive_sys.xc.
References QUICK_STOP_CONTROL.
Referenced by get_next_state().
int read_controlword_switch_on (int control_word)
Definition at line 45 of file drive_sys.xc.
References SWITCH_ON_CONTROL.
Referenced by get_next_state().
void update_checklist (check_list & check_list_param, int mode, chanend c_commutation, chanend c_hall, chanend c_qei, chanend c_adc, chanend c_torque_ctrl, chanend c_velocity_ctrl, chanend c_position_ctrl)
Update Checklist.
Input channel c_commutation for communicating with the commutation server c_hall for communicating with the hall server c_qei for communicating with the qei server c_adc for communicating with the adc server c_torque_ctrl for communicating with the torque control server c_velocity_ctrl for communicating with the velocity control server c_position_ctrl for communicating with the position control server
    Input
Parameters
mode sets mode of operation
Output
Returns
check_list_param updated checklist parameters
Definition at line 131 of file drive_sys.xc.
References __check_adc_init(), __check_commutation_init(), __check_hall_init(), __check_position_init(), __check_qei_init(), __check_torque_init(), __check_velocity_init(), S_Check_list::_adc_init, S_Check_list::_commutation_init, S_Check_list::_hall_init, S_Check_list::_position_init, S_Check_list::_qei_init, S_Check_list::_torque_init, S_Check_list::_velocity_init, S_Check_list::fault, INIT, INIT_BUSY, S_Check_list::mode_op, S_Check_list::operation_enable, S_Check_list::ready, and S_Check_list::switch_on.
Referenced by ecat_motor_drive().
int update_statusword (int current_status, int state_reached, int ack, int q_active, int shutdown_ack)
Definition at line 192 of file drive_sys.xc.
References FAULT_STATE, OPERATION_ENABLED_STATE, QUICK_STOP_STATE, READY_TO_SWITCH_ON_STATE, SWITCH_ON_DISABLED_STATE, SWITCHED_ON_STATE, TARGET_REACHED, and VOLTAGE_ENABLED_STATE.
Referenced by ecat_motor_drive().