sc_sncn_motoctrl_sin: module_sm/src/drive_sys.xc File Reference
drive_sys.xc File Reference
#include <drive_config.h>
#include <internal_config.h>
#include <print.h>
Functions
int read_controlword_switch_on (int control_word)
int read_controlword_quick_stop (int control_word)
int read_controlword_enable_op (int control_word)
int read_controlword_fault_reset (int control_word)
bool __check_commutation_init (chanend c_signal)
Check commutation initialization.
bool __check_hall_init (chanend c_hall)
Check hall initialization.
bool __check_qei_init (chanend c_qei)
Check qei initialization.
bool __check_adc_init ()
Check adc initialization.
bool __check_torque_init (chanend c_torque_ctrl)
Check torque control initialization.
bool __check_velocity_init (chanend c_velocity_ctrl)
Check velocity control initialization.
bool __check_position_init (chanend c_position_ctrl)
Check position control initialization.
check_list init_checklist (void)
Initialize checklist params.
void update_checklist (check_list &check_list_param, int mode, chanend c_commutation, chanend c_hall, chanend c_qei, chanend c_adc, chanend c_torque_ctrl, chanend c_velocity_ctrl, chanend c_position_ctrl)
Update Checklist.
int init_state (void)
int update_statusword (int current_status, int state_reached, int ack, int q_active, int shutdown_ack)
int get_next_state (int in_state, check_list &checklist, int controlword)
Detailed Description
Motor Drive State Machine Implementation
Copyright (c) 2014, Synapticon GmbH All rights reserved. Author: Pavan Kanajar pkana.nosp@m.jar@.nosp@m.synap.nosp@m.tico.nosp@m.n.com
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Execution of this software or parts of it exclusively takes place on hardware produced by Synapticon GmbH.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
The views and conclusions contained in the software and documentation are those of the authors and should not be interpreted as representing official policies, either expressed or implied, of the Synapticon GmbH.
Definition in file drive_sys.xc.
Function Documentation
bool __check_adc_init ()
Check adc initialization.
Output
Returns
init state of the adc loop
Definition at line 85 of file drive_sys.xc.
Referenced by update_checklist().
bool __check_commutation_init (chanend c_signal)
Check commutation initialization.
Output
Returns
init state of the commutation loop
Definition at line 61 of file drive_sys.xc.
References CHECK_BUSY, and init_state().
Referenced by _torque_ctrl(), position_control(), update_checklist(), and velocity_control().
bool __check_hall_init (chanend c_hall)
Check hall initialization.
Output
Returns
init state of the hall loop
Definition at line 69 of file drive_sys.xc.
References CHECK_BUSY, and init_state().
Referenced by update_checklist().
bool __check_position_init (chanend c_position_ctrl)
Check position control initialization.
Output
Returns
init state of the position control loop
Definition at line 104 of file drive_sys.xc.
References CHECK_BUSY, and init_state().
Referenced by set_profile_position(), and update_checklist().
bool __check_qei_init (chanend c_qei)
Check qei initialization.
Output
Returns
init state of the qei loop
Definition at line 77 of file drive_sys.xc.
References CHECK_BUSY, and init_state().
Referenced by update_checklist().
bool __check_torque_init (chanend c_torque_ctrl)
Check torque control initialization.
Output
Returns
init state of the torque control loop
Definition at line 90 of file drive_sys.xc.
References CHECK_BUSY, and init_state().
Referenced by set_profile_torque(), and update_checklist().
bool __check_velocity_init (chanend c_velocity_ctrl)
Check velocity control initialization.
Output
Returns
init state of the velocity control loop
Definition at line 97 of file drive_sys.xc.
References CHECK_BUSY, and init_state().
Referenced by set_profile_velocity(), and update_checklist().
int get_next_state (int in_state, check_list & checklist, int controlword)
Definition at line 244 of file drive_sys.xc.
References S_Check_list::fault, read_controlword_enable_op(), read_controlword_fault_reset(), read_controlword_quick_stop(), read_controlword_switch_on(), S_Check_list::ready, and S_Check_list::switch_on.
Referenced by ecat_motor_drive().
check_list init_checklist (void)
Initialize checklist params.
Output
Returns
check_list initialised checklist parameters
Definition at line 112 of file drive_sys.xc.
References S_Check_list::_adc_init, S_Check_list::_commutation_init, S_Check_list::_hall_init, S_Check_list::_position_init, S_Check_list::_qei_init, S_Check_list::_torque_init, S_Check_list::_velocity_init, S_Check_list::fault, INIT_BUSY, S_Check_list::mode_op, S_Check_list::operation_enable, S_Check_list::ready, and S_Check_list::switch_on.
Referenced by ecat_motor_drive().
int init_state (void)
Definition at line 187 of file drive_sys.xc.
Referenced by __check_commutation_init(), __check_hall_init(), __check_position_init(), __check_qei_init(), __check_torque_init(), __check_velocity_init(), _torque_ctrl(), commutation_client_hanlder(), commutation_init_ecat(), commutation_sinusoidal(), commutation_sinusoidal_loop(), ecat_motor_drive(), hall_client_handler(), hall_init_ecat(), position_control(), qei_client_hanlder(), qei_init_ecat(), run_hall(), run_qei(), send_torque_init_state(), set_profile_position(), set_profile_torque(), set_profile_velocity(), and velocity_control().
int read_controlword_enable_op (int control_word)
Definition at line 53 of file drive_sys.xc.
References ENABLE_OPERATION_CONTROL.
Referenced by get_next_state().
int read_controlword_fault_reset (int control_word)
Definition at line 57 of file drive_sys.xc.
References FAULT_RESET_CONTROL.
Referenced by get_next_state().
int read_controlword_quick_stop (int control_word)
Definition at line 49 of file drive_sys.xc.
References QUICK_STOP_CONTROL.
Referenced by get_next_state().
int read_controlword_switch_on (int control_word)
Definition at line 45 of file drive_sys.xc.
References SWITCH_ON_CONTROL.
Referenced by get_next_state().
void update_checklist (check_list & check_list_param, int mode, chanend c_commutation, chanend c_hall, chanend c_qei, chanend c_adc, chanend c_torque_ctrl, chanend c_velocity_ctrl, chanend c_position_ctrl)
Update Checklist.
Input channel c_commutation for communicating with the commutation server c_hall for communicating with the hall server c_qei for communicating with the qei server c_adc for communicating with the adc server c_torque_ctrl for communicating with the torque control server c_velocity_ctrl for communicating with the velocity control server c_position_ctrl for communicating with the position control server
    Input
Parameters
mode sets mode of operation
Output
Returns
check_list_param updated checklist parameters
Definition at line 131 of file drive_sys.xc.
References __check_adc_init(), __check_commutation_init(), __check_hall_init(), __check_position_init(), __check_qei_init(), __check_torque_init(), __check_velocity_init(), S_Check_list::_adc_init, S_Check_list::_commutation_init, S_Check_list::_hall_init, S_Check_list::_position_init, S_Check_list::_qei_init, S_Check_list::_torque_init, S_Check_list::_velocity_init, S_Check_list::fault, INIT, INIT_BUSY, S_Check_list::mode_op, S_Check_list::operation_enable, S_Check_list::ready, and S_Check_list::switch_on.
Referenced by ecat_motor_drive().
int update_statusword (int current_status, int state_reached, int ack, int q_active, int shutdown_ack)
Definition at line 192 of file drive_sys.xc.
References FAULT_STATE, OPERATION_ENABLED_STATE, QUICK_STOP_STATE, READY_TO_SWITCH_ON_STATE, SWITCH_ON_DISABLED_STATE, SWITCHED_ON_STATE, TARGET_REACHED, and VOLTAGE_ENABLED_STATE.
Referenced by ecat_motor_drive().