sc_sncn_motoctrl_sin: module_ecat_drive/src/ecat_motor_drive.h File Reference
ecat_motor_drive.h File Reference
#include <comm.h>
#include <drive_config.h>
#include <velocity_ctrl_client.h>
#include <position_ctrl_client.h>
#include <torque_ctrl_client.h>
#include <hall_server.h>
#include <hall_client.h>
#include <qei_client.h>
#include <qei_server.h>
#include <profile.h>
Functions
void ecat_motor_drive (chanend pdo_out, chanend pdo_in, chanend coe_out, chanend c_signal, chanend c_hall, chanend c_qei, chanend c_torque_ctrl, chanend c_velocity_ctrl, chanend c_position_ctrl)
This server implementation enables motor drive functions via Ethercat communication.
Detailed Description
Ethercat Motor Drive Server
Copyright (c) 2014, Synapticon GmbH All rights reserved. Author: Pavan Kanajar pkana.nosp@m.jar@.nosp@m.synap.nosp@m.tico.nosp@m.n.com
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Execution of this software or parts of it exclusively takes place on hardware produced by Synapticon GmbH.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
The views and conclusions contained in the software and documentation are those of the authors and should not be interpreted as representing official policies, either expressed or implied, of the Synapticon GmbH.
Definition in file ecat_motor_drive.h.
Function Documentation
void ecat_motor_drive (chanend pdo_out, chanend pdo_in, chanend coe_out, chanend c_signal, chanend c_hall, chanend c_qei, chanend c_torque_ctrl, chanend c_velocity_ctrl, chanend c_position_ctrl)
This server implementation enables motor drive functions via Ethercat communication.
Input Channel pdo_in channel to receive information from ethercat coe_out channel to receive motor config information from ethercat c_signal channel to receive init ack from commutation loop c_hall channel to receive position information from hall c_qei channel to receive position information from qei
Output Channel pdo_out channel to send out information via ethercat c_torque_ctrl channel to receive/send torque control information c_velocity_ctrl channel to receive/send velocity control information c_position_ctrl channel to receive/send position control information
Definition at line 57 of file ecat_motor_drive.xc.
References CYCLIC_SYNCHRONOUS_POSITION_PARAM::base, PROFILE_POSITION_PARAM::base, check_position_ctrl_state(), check_torque_ctrl_state(), check_velocity_ctrl_state(), CSP, CST, CSV, S_QEI::gear_ratio, S_Hall::gear_ratio, get_hall_velocity(), get_next_state(), get_position(), get_target_position(), get_target_torque(), get_target_velocity(), get_torque(), get_velocity(), HALL, HALL_PRECISION, INIT, init_checklist(), init_csp_param(), init_cst_param(), init_csv_param(), init_hall_param(), init_linear_profile(), init_position_control(), init_position_profile(), init_position_profile_limits(), init_pp_params(), init_pt_params(), init_pv_params(), init_qei_param(), init_quick_stop_position_profile(), init_quick_stop_velocity_profile(), init_state(), init_torque_control(), init_velocity_control(), init_velocity_profile(), linear_profile_generate(), PROFILE_POSITION_PARAM::max_acceleration, CYCLIC_SYNCHRONOUS_VELOCITY_PARAM::max_acceleration, CYCLIC_SYNCHRONOUS_VELOCITY_PARAM::max_motor_speed, CYCLIC_SYNCHRONOUS_POSITION_PARAM::max_position_limit, PROFILE_VELOCITY_PARAM::max_profile_velocity, max_speed_limit(), CYCLIC_SYNCHRONOUS_TORQUE_PARAM::max_torque, CYCLIC_SYNCHRONOUS_POSITION_PARAM::min_position_limit, CYCLIC_SYNCHRONOUS_TORQUE_PARAM::motor_torque_constant, MSEC_STD, CYCLIC_SYNCHRONOUS_TORQUE_PARAM::nominal_current, CYCLIC_SYNCHRONOUS_TORQUE_PARAM::polarity, CYCLIC_SYNCHRONOUS_VELOCITY_PARAM::polarity, PROFILE_TORQUE_PARAM::polarity, PROFILE_VELOCITY_PARAM::polarity, S_Hall::pole_pairs, S_QEI::poles, position_factor(), position_limit(), position_profile_generate(), PP, PROFILE_VELOCITY_PARAM::profile_acceleration, PROFILE_VELOCITY_PARAM::profile_deceleration, PROFILE_TORQUE_PARAM::profile_slope, PROFILE_POSITION_PARAM::profile_velocity, PV, QEI, QEI_PRECISION, PROFILE_VELOCITY_PARAM::quick_stop_deceleration, quick_stop_position_profile_generate(), quick_stop_velocity_profile_generate(), S_QEI::real_counts, SEC_STD, send_actual_position(), send_actual_torque(), send_actual_velocity(), set_commutation_param_ecat(), set_hall_param_ecat(), set_position(), set_position_csp(), set_position_ctrl_hall_param(), set_position_ctrl_param(), set_position_ctrl_qei_param(), set_position_sensor(), set_qei_param_ecat(), set_torque(), set_torque_cst(), set_torque_ctrl_hall_param(), set_torque_ctrl_param(), set_torque_ctrl_qei_param(), set_torque_sensor(), set_velocity(), set_velocity_csv(), set_velocity_ctrl_hall_param(), set_velocity_ctrl_param(), set_velocity_ctrl_qei_param(), set_velocity_sensor(), shutdown_position_ctrl(), shutdown_torque_ctrl(), shutdown_velocity_ctrl(), PROFILE_POSITION_PARAM::software_position_limit_max, PROFILE_POSITION_PARAM::software_position_limit_min, TQ, update_checklist(), update_csp_param_ecat(), update_cst_param_ecat(), update_csv_param_ecat(), update_hall_param_ecat(), update_position_ctrl_param_ecat(), update_pp_param_ecat(), update_pt_param_ecat(), update_pv_param_ecat(), update_qei_param_ecat(), update_statusword(), update_torque_ctrl_param_ecat(), update_velocity_ctrl_param_ecat(), velocity_profile_generate(), and xscope_initialise().
Referenced by main().