sc_sncn_motoctrl_sin: module_blocks/src/filter_blocks/filter_blocks.xc File Reference
filter_blocks.xc File Reference
Moving Average Filter Implementation.
#include "filter_blocks.h"
Functions
void init_filter (int filter_buffer[], int &index, int filter_length)
Initialise Moving Average Filter Parameters.
int filter (int filter_buffer[], int &index, int filter_length, int input)
Get moving average filtered output by passing the sampled data to be filtered as input.
int _modified_internal_filter (int filter_buffer[], int &index, int filter_length, int input)
Detailed Description
Moving Average Filter Implementation.
Author
: Pavan Kanajar pkana.nosp@m.jar@.nosp@m.synap.nosp@m.tico.nosp@m.n.com
Definition in file filter_blocks.xc.
Function Documentation
int _modified_internal_filter (int filter_buffer[], int & index, int filter_length, int input)
Definition at line 76 of file filter_blocks.xc.
Referenced by run_hall().
int filter (int filter_buffer[], int & index, int filter_length, int input)
Get moving average filtered output by passing the sampled data to be filtered as input.
Parameters
filter_buffer
index
filter_length defines the length of the filter
input data sampled at fixed time
Returns
filtered output
Definition at line 58 of file filter_blocks.xc.
Referenced by velocity_control().
void init_filter (int filter_buffer[], int & index, int filter_length)
Initialise Moving Average Filter Parameters.
Parameters
filter_buffer array to initialized
index
filter_length defines the length of the filter
Definition at line 47 of file filter_blocks.xc.
Referenced by init_qei_velocity_params(), run_hall(), and velocity_control().