sc_sncn_motoctrl_sin: module_hall/src/hall_server.xc File Reference
hall_server.xc File Reference
#include "hall_server.h"
Macros
#define defPeriodMax 1000000
Functions
void hall_client_handler (chanend c_hall, int command, int angle, int raw_velocity, int init_state, int count, int direction, hall_par &hall_params, int &status)
void run_hall (chanend c_hall_p1, chanend c_hall_p2, chanend c_hall_p3, chanend c_hall_p4, chanend c_hall_p5, port in p_hall, hall_par &hall_params)
A basic hall encoder server.
Detailed Description
Hall Sensor Server
Copyright (c) 2014, Synapticon GmbH All rights reserved. Author: Pavan Kanajar pkana.nosp@m.jar@.nosp@m.synap.nosp@m.tico.nosp@m.n.com, Ludwig Orgler lorgl.nosp@m.er@s.nosp@m.ynapt.nosp@m.icon.nosp@m..com & Martin Schwarz mschw.nosp@m.arz@.nosp@m.synap.nosp@m.tico.nosp@m.n.com
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Execution of this software or parts of it exclusively takes place on hardware produced by Synapticon GmbH.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
The views and conclusions contained in the software and documentation are those of the authors and should not be interpreted as representing official policies, either expressed or implied, of the Synapticon GmbH.
Definition in file hall_server.xc.
Macro Definition Documentation
#define defPeriodMax 1000000
Referenced by run_hall().
Function Documentation
void hall_client_handler (chanend c_hall, int command, int angle, int raw_velocity, int init_state, int count, int direction, hall_par & hall_params, int & status)
Definition at line 43 of file hall_server.xc.
References CHECK_BUSY, S_Hall::gear_ratio, HALL_ABSOLUTE_POS_REQ, HALL_POS_REQ, HALL_VELOCITY_REQ, init_state(), S_Hall::pole_pairs, and SET_HALL_PARAM_ECAT.
Referenced by run_hall().
void run_hall (chanend c_hall_p1, chanend c_hall_p2, chanend c_hall_p3, chanend c_hall_p4, chanend c_hall_p5, port in p_hall, hall_par & hall_params)
A basic hall encoder server.
This implements the basic hall sensor server
Output channel
\channel c_hall_p1 the control channel for reading hall position in order of priority (highest) 1 ... (lowest) 5
c_hall_p2 the control channel for reading hall position (priority 2) c_hall_p3 the control channel for reading hall position (priority 3) c_hall_p4 the control channel for reading hall position (priority 4) c_hall_p5 the control channel for reading hall position (priority 5)
Input port
\port p_hall the port for reading the hall sensor data
 Input
\param hall_params struct defines the pole-pairs and gear ratio
Definition at line 76 of file hall_server.xc.
References _modified_internal_filter(), defPeriodMax, FILTER_LENGTH_HALL, S_Hall::gear_ratio, hall_client_handler(), INIT, init_filter(), init_state(), MSEC_FAST, and S_Hall::pole_pairs.
Referenced by main().