sc_sncn_motoctrl_sin: module_ctrl_loops/position/position_ctrl_client.xc File Reference
position_ctrl_client.xc File Reference
#include <position_ctrl_client.h>
#include <print.h>
#include <drive_config.h>
Functions
int init_position_control (chanend c_position_ctrl)
Initialise Position Control Loop.
void set_position (int target_position, chanend c_position_ctrl)
Set new target position for position control.
int get_position (chanend c_position_ctrl)
Get actual position from position control.
int position_limit (int position, int max_position_limit, int min_position_limit)
Position Limiter.
void set_position_csp (csp_par &csp_params, int target_position, int position_offset, int velocity_offset, int torque_offset, chanend c_position_ctrl)
Set new target position for position control (advanced function)
void set_position_ctrl_param (ctrl_par &position_ctrl_params, chanend c_position_ctrl)
Set Position Control PID Parameters.
void set_position_ctrl_hall_param (hall_par &hall_params, chanend c_position_ctrl)
Set hall sensor parameters for Position Control.
void set_position_ctrl_qei_param (qei_par &qei_params, chanend c_position_ctrl)
Set QEI sensor for Position Control.
void set_position_sensor (int sensor_used, chanend c_position_ctrl)
Sets the sensor used for Position Control.
void enable_position_ctrl (chanend c_position_ctrl)
Enables Position Control mode operation.
void shutdown_position_ctrl (chanend c_position_ctrl)
Shutdown Position Control mode operation.
int check_position_ctrl_state (chanend c_position_ctrl)
Checks Position Control Loop Status.
Detailed Description
Position control Loop Client functions
Copyright (c) 2014, Synapticon GmbH All rights reserved. Author: Pavan Kanajar pkana.nosp@m.jar@.nosp@m.synap.nosp@m.tico.nosp@m.n.com
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Execution of this software or parts of it exclusively takes place on hardware produced by Synapticon GmbH.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
The views and conclusions contained in the software and documentation are those of the authors and should not be interpreted as representing official policies, either expressed or implied, of the Synapticon GmbH.
Definition in file position_ctrl_client.xc.
Function Documentation
int check_position_ctrl_state (chanend c_position_ctrl)
Checks Position Control Loop Status.
Input Channel c_position_ctrl channel to get state of control loop
Output
Returns
state of the control loop : 1 - active, 0 - inactive
Definition at line 160 of file position_ctrl_client.xc.
References POSITION_CTRL_READ, POSITION_CTRL_STATUS, and POSITION_CTRL_WRITE.
Referenced by ecat_motor_drive(), and init_position_control().
void enable_position_ctrl (chanend c_position_ctrl)
Enables Position Control mode operation.
c_position_ctrl channel to signal enable position control
Definition at line 148 of file position_ctrl_client.xc.
References ENABLE_POSITION_CTRL, and POSITION_CTRL_WRITE.
Referenced by init_position_control().
int get_position (chanend c_position_ctrl)
Get actual position from position control.
Output Channel c_position_ctrl channel to receive actual position
Output
Returns
actual position from position control
Definition at line 79 of file position_ctrl_client.xc.
References GET_POSITION_TOKEN, POSITION_CTRL_READ, and POSITION_CTRL_WRITE.
Referenced by ecat_motor_drive(), and set_profile_position().
int init_position_control (chanend c_position_ctrl)
Initialise Position Control Loop.
Input Channel c_position_ctrl channel to signal initialisation
Definition at line 49 of file position_ctrl_client.xc.
References check_position_ctrl_state(), enable_position_ctrl(), INIT, and INIT_BUSY.
Referenced by ecat_motor_drive(), and set_profile_position().
int position_limit (int position, int max_position_limit, int min_position_limit)
Position Limiter.
Input
Parameters
position is the input position to be limited in range
max_position_limit is the max position that can be reached
min_position_limit is the min position that can be reached
Output
Returns
position in the range [min_position_limit - max_position_limit]
Definition at line 87 of file position_ctrl_client.xc.
Referenced by ecat_motor_drive(), set_position_csp(), and set_profile_position().
void set_position (int target_position, chanend c_position_ctrl)
Set new target position for position control.
Input Channel c_position_ctrl channel to signal new target position
Input
Parameters
target_position is the new target position
Definition at line 72 of file position_ctrl_client.xc.
References POSITION_CTRL_WRITE, and SET_POSITION_TOKEN.
Referenced by ecat_motor_drive(), set_position_csp(), and set_profile_position().
void set_position_csp (csp_par & csp_params, int target_position, int position_offset, int velocity_offset, int torque_offset, chanend c_position_ctrl)
Set new target position for position control (advanced function)
Input Channel c_position_ctrl channel to signal new target position
Input
Parameters
csp_param struct defines the motor parameters and position limits
target_position is the new target position
position_offset defines offset in position
velocity_offset defines offset in velocity
torque_offset defines offset in torque
Definition at line 104 of file position_ctrl_client.xc.
References CYCLIC_SYNCHRONOUS_POSITION_PARAM::base, CYCLIC_SYNCHRONOUS_POSITION_PARAM::max_position_limit, CYCLIC_SYNCHRONOUS_POSITION_PARAM::min_position_limit, CYCLIC_SYNCHRONOUS_VELOCITY_PARAM::polarity, position_limit(), and set_position().
Referenced by ecat_motor_drive().
void set_position_ctrl_hall_param (hall_par & hall_params, chanend c_position_ctrl)
Set hall sensor parameters for Position Control.
Parameters
hall_params struct defines the pole-pairs and gear ratio
Definition at line 125 of file position_ctrl_client.xc.
References S_Hall::gear_ratio, S_Hall::pole_pairs, and SET_POSITION_CTRL_HALL.
Referenced by ecat_motor_drive().
void set_position_ctrl_param (ctrl_par & position_ctrl_params, chanend c_position_ctrl)
Set Position Control PID Parameters.
Input
Parameters
position_ctrl_params struct defines the position control PID parameters
Definition at line 113 of file position_ctrl_client.xc.
References S_Control::Integral_limit, S_Control::Kd_d, S_Control::Kd_n, S_Control::Ki_d, S_Control::Ki_n, S_Control::Kp_d, S_Control::Kp_n, POSITION_CTRL_WRITE, and SET_CTRL_PARAMETER.
Referenced by ecat_motor_drive().
void set_position_ctrl_qei_param (qei_par & qei_params, chanend c_position_ctrl)
Set QEI sensor for Position Control.
Parameters
qei_params struct defines the quadrature encoder (QEI) resolution, sensor type and gear-ratio used for the motor
Definition at line 132 of file position_ctrl_client.xc.
References S_QEI::gear_ratio, S_QEI::index, S_QEI::max_count, S_QEI::real_counts, and SET_POSITION_CTRL_QEI.
Referenced by ecat_motor_drive().
void set_position_sensor (int sensor_used, chanend c_position_ctrl)
Sets the sensor used for Position Control.
Parameters
sensor_used defines the sensor to be used (HALL/QEI) for Position Control
Definition at line 142 of file position_ctrl_client.xc.
References POSITION_CTRL_WRITE, and SENSOR_SELECT.
Referenced by ecat_motor_drive().
void shutdown_position_ctrl (chanend c_position_ctrl)
Shutdown Position Control mode operation.
c_position_ctrl channel to signal shutdown of position control
Definition at line 154 of file position_ctrl_client.xc.
References POSITION_CTRL_WRITE, and SHUTDOWN_POSITION_CTRL.
Referenced by ecat_motor_drive().