sc_sncn_motoctrl_sin: module_profile/profile_position_mode/profile_position.c File Reference
profile_position.c File Reference
Profile Generation for Position Implements position profile based on Linear Function with Parabolic Blends.
#include <profile.h>
Data Structures
struct PROFILE_POSITION_PARAM
struct definition for profile position param
Functions
void init_position_profile_limits (int gear_ratio, int max_acceleration, int max_velocity)
Initialise Position Profile Limits.
int init_position_profile (int target_position, int actual_position, int velocity, int acceleration, int deceleration)
Initialise Position Profile.
int position_profile_generate (int step)
Generate Position Profile.
Variables
struct PROFILE_POSITION_PARAM profile_pos_params
Detailed Description
Profile Generation for Position Implements position profile based on Linear Function with Parabolic Blends.
Copyright (c) 2014, Synapticon GmbH All rights reserved. Author: Pavan Kanajar pkana.nosp@m.jar@.nosp@m.synap.nosp@m.tico.nosp@m.n.com
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Execution of this software or parts of it exclusively takes place on hardware produced by Synapticon GmbH.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
The views and conclusions contained in the software and documentation are those of the authors and should not be interpreted as representing official policies, either expressed or implied, of the Synapticon GmbH.
Definition in file profile_position.c.
Function Documentation
int init_position_profile (int target_position, int actual_position, int velocity, int acceleration, int deceleration)
Initialise Position Profile.
Input
Parameters
target_position
actual_position
velocity for the position profile
acceleration for the position profile
deceleration for the position profile
Output
Returns
no. of steps for position profile : range [1 - steps]
Definition at line 107 of file profile_position.c.
References PROFILE_POSITION_PARAM::acc, PROFILE_POSITION_PARAM::acc_min, PROFILE_POSITION_PARAM::acc_too_low, PROFILE_POSITION_PARAM::ai, PROFILE_POSITION_PARAM::bi, PROFILE_POSITION_PARAM::ci, PROFILE_POSITION_PARAM::dec, PROFILE_POSITION_PARAM::di, PROFILE_POSITION_PARAM::direction, PROFILE_POSITION_PARAM::distance_acc, PROFILE_POSITION_PARAM::distance_cruise, PROFILE_POSITION_PARAM::distance_dec, PROFILE_POSITION_PARAM::distance_left, PROFILE_POSITION_PARAM::ei, PROFILE_POSITION_PARAM::fi, PROFILE_POSITION_PARAM::gear_ratio, PROFILE_POSITION_PARAM::gi, PROFILE_POSITION_PARAM::max_acceleration, PROFILE_POSITION_PARAM::max_velocity, profile_pos_params, PROFILE_POSITION_PARAM::qf, PROFILE_POSITION_PARAM::qfd, PROFILE_POSITION_PARAM::qi, PROFILE_POSITION_PARAM::qid, PROFILE_POSITION_PARAM::s_time, PROFILE_POSITION_PARAM::T, PROFILE_POSITION_PARAM::t_cruise, PROFILE_POSITION_PARAM::tb_acc, PROFILE_POSITION_PARAM::tb_dec, PROFILE_POSITION_PARAM::tf, PROFILE_POSITION_PARAM::total_distance, and PROFILE_POSITION_PARAM::vi.
Referenced by ecat_motor_drive(), and set_profile_position().
void init_position_profile_limits (int gear_ratio, int max_acceleration, int max_velocity)
Initialise Position Profile Limits.
Input
Parameters
gear_ratio
max_acceleration for the position profile
max_velocity for the position profile
Definition at line 100 of file profile_position.c.
References PROFILE_POSITION_PARAM::gear_ratio, PROFILE_POSITION_PARAM::max_acceleration, PROFILE_POSITION_PARAM::max_velocity, and profile_pos_params.
Referenced by ecat_motor_drive(), and position_profile_test().
int position_profile_generate (int step)
Generate Position Profile.
Input
Parameters
step current step of the profile
Output
Returns
corresponding target position at the step input
Definition at line 311 of file profile_position.c.
References PROFILE_POSITION_PARAM::ai, PROFILE_POSITION_PARAM::bi, PROFILE_POSITION_PARAM::ci, PROFILE_POSITION_PARAM::di, PROFILE_POSITION_PARAM::ei, PROFILE_POSITION_PARAM::fi, PROFILE_POSITION_PARAM::gi, profile_pos_params, PROFILE_POSITION_PARAM::q, PROFILE_POSITION_PARAM::s_time, PROFILE_POSITION_PARAM::tb_acc, PROFILE_POSITION_PARAM::tb_dec, PROFILE_POSITION_PARAM::tf, PROFILE_POSITION_PARAM::ts, and PROFILE_POSITION_PARAM::vi.
Referenced by ecat_motor_drive(), and set_profile_position().
Variable Documentation
struct PROFILE_POSITION_PARAM profile_pos_params
Referenced by init_position_profile(), init_position_profile_limits(), and position_profile_generate().