sc_sncn_motoctrl_sin: module_profile/include/profile_control.h File Reference
profile_control.h File Reference
Profile Control functions Implements position profile control, velocity profile control and torque profile control functions.
#include <xs1.h>
#include <platform.h>
#include <bldc_motor_config.h>
Functions
void set_profile_position (int target_position, int velocity, int acceleration, int deceleration, int max_position, int min_position, chanend c_position_ctrl)
Set profile position with Position Control loop.
void set_profile_velocity (int target_velocity, int acceleration, int deceleration, int max_profile_velocity, chanend c_velocity_ctrl)
Set profile velocity with Velocity Control loop.
void set_profile_torque (int target_torque, int torque_slope, cst_par &cst_params, chanend c_torque_ctrl)
Set profile torque with Torque Control loop.
Detailed Description
Profile Control functions Implements position profile control, velocity profile control and torque profile control functions.
Copyright (c) 2014, Synapticon GmbH All rights reserved. Author: Pavan Kanajar pkana.nosp@m.jar@.nosp@m.synap.nosp@m.tico.nosp@m.n.com
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Execution of this software or parts of it exclusively takes place on hardware produced by Synapticon GmbH.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
The views and conclusions contained in the software and documentation are those of the authors and should not be interpreted as representing official policies, either expressed or implied, of the Synapticon GmbH.
Definition in file profile_control.h.
Function Documentation
void set_profile_position (int target_position, int velocity, int acceleration, int deceleration, int max_position, int min_position, chanend c_position_ctrl)
Set profile position with Position Control loop.
Output channel c_position_ctrl for communicating with the Position Control Server
Input
Parameters
target_position is the new target position in (degree)
velocity in (rpm)
acceleration in (rpm/s)
deceleration in (rpm/s)
min position in (degree)
max position in (degree)
Definition at line 51 of file profile_position.xc.
References __check_position_init(), get_position(), INIT, INIT_BUSY, init_position_control(), init_position_profile(), init_state(), MSEC_STD, position_limit(), position_profile_generate(), and set_position().
Referenced by position_profile_test().
void set_profile_torque (int target_torque, int torque_slope, cst_par & cst_params, chanend c_torque_ctrl)
Set profile torque with Torque Control loop.
Output channel c_torque_ctrl for communicating with the Torque Control Server
Input
Parameters
target_torque is the new target torque in (mNm * current resolution)
torque_slope in (mNm/s * current resolution)
cst_params struct defines cyclic synchronous torque params
Definition at line 51 of file profile_torque.xc.
References __check_torque_init(), get_torque(), INIT, INIT_BUSY, init_linear_profile(), init_state(), init_torque_control(), linear_profile_generate(), CYCLIC_SYNCHRONOUS_TORQUE_PARAM::max_torque, MSEC_STD, CYCLIC_SYNCHRONOUS_TORQUE_PARAM::polarity, and set_torque().
Referenced by profile_torque_test().
void set_profile_velocity (int target_velocity, int acceleration, int deceleration, int max_profile_velocity, chanend c_velocity_ctrl)
Set profile velocity with Velocity Control loop.
Output channel c_velocity_ctrl for communicating with the Velocity Control Server
Input
Parameters
target_velocity is the new target velocity in (rpm)
acceleration in (rpm/s)
deceleration in (rpm/s)
max_profile_velocity is max velocity for the profile in (rpm)
Definition at line 51 of file profile_velocity.xc.
References __check_velocity_init(), get_velocity(), INIT, INIT_BUSY, init_state(), init_velocity_control(), init_velocity_profile(), MSEC_STD, set_velocity(), and velocity_profile_generate().
Referenced by profile_velocity_test().