sc_sncn_motoctrl_sin: module_profile/profile_linear_mode/profile_linear.c File Reference
profile_linear.c File Reference
Profile Generation Implements Torque profile based on linear functions.
#include <profile.h>
#include <stdio.h>
Data Structures
struct PROFILE_LINEAR_PARAM
Functions
int init_linear_profile (int target_value, int actual_value, int acceleration, int deceleration, int max_value)
Initialise Linear Profile.
int linear_profile_generate (int step)
Generate Linear Profile.
int init_linear_profile_float (float target_value, float actual_value, float acceleration, float deceleration, float max_value)
float linear_profile_generate_float (int step)
Variables
struct PROFILE_LINEAR_PARAM profile_linear_params
Detailed Description
Profile Generation Implements Torque profile based on linear functions.
Copyright (c) 2014, Synapticon GmbH All rights reserved. Author: Pavan Kanajar pkana.nosp@m.jar@.nosp@m.synap.nosp@m.tico.nosp@m.n.com
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Execution of this software or parts of it exclusively takes place on hardware produced by Synapticon GmbH.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
The views and conclusions contained in the software and documentation are those of the authors and should not be interpreted as representing official policies, either expressed or implied, of the Synapticon GmbH.
Definition in file profile_linear.c.
Function Documentation
int init_linear_profile (int target_value, int actual_value, int acceleration, int deceleration, int max_value)
Initialise Linear Profile.
Input
Parameters
target_value
actual_value
acceleration for the Linear profile
deceleration for the Linear profile
max_value for the Linear profile
Output
Returns
no. of steps for linear profile : range [1 - steps]
Definition at line 61 of file profile_linear.c.
References PROFILE_LINEAR_PARAM::a_d, PROFILE_LINEAR_PARAM::acc, PROFILE_LINEAR_PARAM::dec, PROFILE_LINEAR_PARAM::oldst, profile_linear_params, PROFILE_LINEAR_PARAM::s_time, PROFILE_LINEAR_PARAM::t, PROFILE_LINEAR_PARAM::T, PROFILE_LINEAR_PARAM::u, and PROFILE_LINEAR_PARAM::v_d.
Referenced by ecat_motor_drive(), and set_profile_torque().
int init_linear_profile_float (float target_value, float actual_value, float acceleration, float deceleration, float max_value)
Definition at line 165 of file profile_linear.c.
References PROFILE_LINEAR_PARAM::a_d, PROFILE_LINEAR_PARAM::acc, PROFILE_LINEAR_PARAM::dec, PROFILE_LINEAR_PARAM::oldst, profile_linear_params, PROFILE_LINEAR_PARAM::s_time, PROFILE_LINEAR_PARAM::t, PROFILE_LINEAR_PARAM::T, PROFILE_LINEAR_PARAM::u, and PROFILE_LINEAR_PARAM::v_d.
int linear_profile_generate (int step)
Generate Linear Profile.
Input
Parameters
step current step of the profile
Output
Returns
corresponding target value at the step input
Definition at line 160 of file profile_linear.c.
References PROFILE_LINEAR_PARAM::a_d, profile_linear_params, PROFILE_LINEAR_PARAM::s_time, and PROFILE_LINEAR_PARAM::u.
Referenced by ecat_motor_drive(), and set_profile_torque().
float linear_profile_generate_float (int step)
Definition at line 264 of file profile_linear.c.
References PROFILE_LINEAR_PARAM::a_d, profile_linear_params, PROFILE_LINEAR_PARAM::s_time, and PROFILE_LINEAR_PARAM::u.
Variable Documentation
struct PROFILE_LINEAR_PARAM profile_linear_params
Referenced by init_linear_profile(), init_linear_profile_float(), linear_profile_generate(), and linear_profile_generate_float().