sc_sncn_motoctrl_sin: module_profile/profile_velocity_mode/profile_velocity.c File Reference
profile_velocity.c File Reference
Profile Generation for Velocity Implements velocity profile based on linear functions.
#include <profile.h>
#include <stdio.h>
Data Structures
struct PROFILE_VELOCITY_PARAM
struct definition for profile velocity param
Functions
int init_velocity_profile (int target_velocity, int actual_velocity, int acceleration, int deceleration, int max_velocity)
Initialise Velocity Profile.
int velocity_profile_generate (int step)
Generate Velocity Profile.
Variables
struct PROFILE_VELOCITY_PARAM profile_vel_params
Detailed Description
Profile Generation for Velocity Implements velocity profile based on linear functions.
Copyright (c) 2014, Synapticon GmbH All rights reserved. Author: Pavan Kanajar pkana.nosp@m.jar@.nosp@m.synap.nosp@m.tico.nosp@m.n.com
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Execution of this software or parts of it exclusively takes place on hardware produced by Synapticon GmbH.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
The views and conclusions contained in the software and documentation are those of the authors and should not be interpreted as representing official policies, either expressed or implied, of the Synapticon GmbH.
Definition in file profile_velocity.c.
Function Documentation
int init_velocity_profile (int target_velocity, int actual_velocity, int acceleration, int deceleration, int max_velocity)
Initialise Velocity Profile.
Input
Parameters
target_velocity
actual_velocity
acceleration for the velocity profile
deceleration for the velocity profile
max_velocity for the velocity profile
Output
Returns
no. of steps for velocity profile : range [1 - steps]
Definition at line 59 of file profile_velocity.c.
References PROFILE_VELOCITY_PARAM::a_d, PROFILE_VELOCITY_PARAM::acc, PROFILE_VELOCITY_PARAM::dec, PROFILE_VELOCITY_PARAM::oldst, profile_vel_params, PROFILE_VELOCITY_PARAM::s_time, PROFILE_VELOCITY_PARAM::t, PROFILE_VELOCITY_PARAM::T, PROFILE_VELOCITY_PARAM::u, and PROFILE_VELOCITY_PARAM::v_d.
Referenced by ecat_motor_drive(), and set_profile_velocity().
int velocity_profile_generate (int step)
Generate Velocity Profile.
Input
Parameters
step current step of the profile
Output
Returns
corresponding target velocity at the step input
Definition at line 156 of file profile_velocity.c.
References PROFILE_VELOCITY_PARAM::a_d, profile_vel_params, PROFILE_VELOCITY_PARAM::s_time, and PROFILE_VELOCITY_PARAM::u.
Referenced by ecat_motor_drive(), and set_profile_velocity().
Variable Documentation
struct PROFILE_VELOCITY_PARAM profile_vel_params
Referenced by init_velocity_profile(), and velocity_profile_generate().