sc_sncn_motoctrl_sin: module_profile/include/profile.h File Reference
profile.h File Reference
Profile Generation for Position, Velocity and Torque Implements position profile based on Linear Function with Parabolic Blends, velocity profile and torque profiles are based on linear functions.
#include <stdio.h>
#include <math.h>
Functions
int init_quick_stop_velocity_profile (int actual_velocity, int quick_stop_deceleration)
Initialise Quick Stop Velocity Profile.
int quick_stop_velocity_profile_generate (int step)
Generate Quick Stop Velocity Profile.
int init_velocity_profile (int target_velocity, int actual_velocity, int acceleration, int deceleration, int max_velocity)
Initialise Velocity Profile.
int velocity_profile_generate (int step)
Generate Velocity Profile.
void init_position_profile_limits (int gear_ratio, int max_acceleration, int max_velocity)
Initialise Position Profile Limits.
int init_position_profile (int target_position, int actual_position, int velocity, int acceleration, int deceleration)
Initialise Position Profile.
int position_profile_generate (int step)
Generate Position Profile.
int init_quick_stop_position_profile (int actual_velocity, int actual_position, int max_acceleration)
Initialise Quick Stop Position Profile.
int quick_stop_position_profile_generate (int steps, int actual_velocity)
Generate Quick Stop Position Profile.
int init_linear_profile (int target_value, int actual_value, int acceleration, int deceleration, int max_value)
Initialise Linear Profile.
int linear_profile_generate (int step)
Generate Linear Profile.
int init_linear_profile_float (float target_value, float actual_value, float acceleration, float deceleration, float max_value)
float linear_profile_generate_float (int step)
Detailed Description
Profile Generation for Position, Velocity and Torque Implements position profile based on Linear Function with Parabolic Blends, velocity profile and torque profiles are based on linear functions.
Copyright (c) 2014, Synapticon GmbH All rights reserved. Author: Pavan Kanajar pkana.nosp@m.jar@.nosp@m.synap.nosp@m.tico.nosp@m.n.com
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Execution of this software or parts of it exclusively takes place on hardware produced by Synapticon GmbH.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
The views and conclusions contained in the software and documentation are those of the authors and should not be interpreted as representing official policies, either expressed or implied, of the Synapticon GmbH.
Definition in file profile.h.
Function Documentation
int init_linear_profile (int target_value, int actual_value, int acceleration, int deceleration, int max_value)
Initialise Linear Profile.
Input
Parameters
target_value
actual_value
acceleration for the Linear profile
deceleration for the Linear profile
max_value for the Linear profile
Output
Returns
no. of steps for linear profile : range [1 - steps]
Definition at line 61 of file profile_linear.c.
References PROFILE_LINEAR_PARAM::a_d, PROFILE_LINEAR_PARAM::acc, PROFILE_LINEAR_PARAM::dec, PROFILE_LINEAR_PARAM::oldst, profile_linear_params, PROFILE_LINEAR_PARAM::s_time, PROFILE_LINEAR_PARAM::t, PROFILE_LINEAR_PARAM::T, PROFILE_LINEAR_PARAM::u, and PROFILE_LINEAR_PARAM::v_d.
Referenced by ecat_motor_drive(), and set_profile_torque().
int init_linear_profile_float (float target_value, float actual_value, float acceleration, float deceleration, float max_value)
Definition at line 165 of file profile_linear.c.
References PROFILE_LINEAR_PARAM::a_d, PROFILE_LINEAR_PARAM::acc, PROFILE_LINEAR_PARAM::dec, PROFILE_LINEAR_PARAM::oldst, profile_linear_params, PROFILE_LINEAR_PARAM::s_time, PROFILE_LINEAR_PARAM::t, PROFILE_LINEAR_PARAM::T, PROFILE_LINEAR_PARAM::u, and PROFILE_LINEAR_PARAM::v_d.
int init_position_profile (int target_position, int actual_position, int velocity, int acceleration, int deceleration)
Initialise Position Profile.
Input
Parameters
target_position
actual_position
velocity for the position profile
acceleration for the position profile
deceleration for the position profile
Output
Returns
no. of steps for position profile : range [1 - steps]
Definition at line 107 of file profile_position.c.
References PROFILE_POSITION_PARAM::acc, PROFILE_POSITION_PARAM::acc_min, PROFILE_POSITION_PARAM::acc_too_low, PROFILE_POSITION_PARAM::ai, PROFILE_POSITION_PARAM::bi, PROFILE_POSITION_PARAM::ci, PROFILE_POSITION_PARAM::dec, PROFILE_POSITION_PARAM::di, PROFILE_POSITION_PARAM::direction, PROFILE_POSITION_PARAM::distance_acc, PROFILE_POSITION_PARAM::distance_cruise, PROFILE_POSITION_PARAM::distance_dec, PROFILE_POSITION_PARAM::distance_left, PROFILE_POSITION_PARAM::ei, PROFILE_POSITION_PARAM::fi, PROFILE_POSITION_PARAM::gear_ratio, PROFILE_POSITION_PARAM::gi, PROFILE_POSITION_PARAM::max_acceleration, PROFILE_POSITION_PARAM::max_velocity, profile_pos_params, PROFILE_POSITION_PARAM::qf, PROFILE_POSITION_PARAM::qfd, PROFILE_POSITION_PARAM::qi, PROFILE_POSITION_PARAM::qid, PROFILE_POSITION_PARAM::s_time, PROFILE_POSITION_PARAM::T, PROFILE_POSITION_PARAM::t_cruise, PROFILE_POSITION_PARAM::tb_acc, PROFILE_POSITION_PARAM::tb_dec, PROFILE_POSITION_PARAM::tf, PROFILE_POSITION_PARAM::total_distance, and PROFILE_POSITION_PARAM::vi.
Referenced by ecat_motor_drive(), and set_profile_position().
void init_position_profile_limits (int gear_ratio, int max_acceleration, int max_velocity)
Initialise Position Profile Limits.
Input
Parameters
gear_ratio
max_acceleration for the position profile
max_velocity for the position profile
Definition at line 100 of file profile_position.c.
References PROFILE_POSITION_PARAM::gear_ratio, PROFILE_POSITION_PARAM::max_acceleration, PROFILE_POSITION_PARAM::max_velocity, and profile_pos_params.
Referenced by ecat_motor_drive(), and position_profile_test().
int init_quick_stop_position_profile (int actual_velocity, int actual_position, int max_acceleration)
Initialise Quick Stop Position Profile.
Input
Parameters
actual_velocity
actual_position
max_acceleration defines the deceleration for quick stop profile
Output
Returns
no. of steps for quick stop profile : range [1 - steps]
Definition at line 75 of file profile_position_quick-stop.c.
References pos_params::acc, pos_params::ci, pos_params::cur_pos_s, pos_param_s, pos_params::qf, pos_params::qi, pos_params::samp, pos_params::t_int, and pos_params::tb.
Referenced by ecat_motor_drive().
int init_quick_stop_velocity_profile (int actual_velocity, int quick_stop_deceleration)
Initialise Quick Stop Velocity Profile.
Input
Parameters
actual_velocity
quick_stop_deceleration defines the deceleration for quick stop profile
Output
Returns
no. of steps for quick stop profile : range [1 - steps]
Definition at line 53 of file profile_velocity_quick-stop.c.
References QUICK_STOP_VELOCITY_PARAM::a_d, qstop_vel_params, QUICK_STOP_VELOCITY_PARAM::s_time, QUICK_STOP_VELOCITY_PARAM::t, QUICK_STOP_VELOCITY_PARAM::T, and QUICK_STOP_VELOCITY_PARAM::u.
Referenced by ecat_motor_drive().
int init_velocity_profile (int target_velocity, int actual_velocity, int acceleration, int deceleration, int max_velocity)
Initialise Velocity Profile.
Input
Parameters
target_velocity
actual_velocity
acceleration for the velocity profile
deceleration for the velocity profile
max_velocity for the velocity profile
Output
Returns
no. of steps for velocity profile : range [1 - steps]
Definition at line 59 of file profile_velocity.c.
References PROFILE_VELOCITY_PARAM::a_d, PROFILE_VELOCITY_PARAM::acc, PROFILE_VELOCITY_PARAM::dec, PROFILE_VELOCITY_PARAM::oldst, profile_vel_params, PROFILE_VELOCITY_PARAM::s_time, PROFILE_VELOCITY_PARAM::t, PROFILE_VELOCITY_PARAM::T, PROFILE_VELOCITY_PARAM::u, and PROFILE_VELOCITY_PARAM::v_d.
Referenced by ecat_motor_drive(), and set_profile_velocity().
int linear_profile_generate (int step)
Generate Linear Profile.
Input
Parameters
step current step of the profile
Output
Returns
corresponding target value at the step input
Definition at line 160 of file profile_linear.c.
References PROFILE_LINEAR_PARAM::a_d, profile_linear_params, PROFILE_LINEAR_PARAM::s_time, and PROFILE_LINEAR_PARAM::u.
Referenced by ecat_motor_drive(), and set_profile_torque().
float linear_profile_generate_float (int step)
Definition at line 264 of file profile_linear.c.
References PROFILE_LINEAR_PARAM::a_d, profile_linear_params, PROFILE_LINEAR_PARAM::s_time, and PROFILE_LINEAR_PARAM::u.
int position_profile_generate (int step)
Generate Position Profile.
Input
Parameters
step current step of the profile
Output
Returns
corresponding target position at the step input
Definition at line 311 of file profile_position.c.
References PROFILE_POSITION_PARAM::ai, PROFILE_POSITION_PARAM::bi, PROFILE_POSITION_PARAM::ci, PROFILE_POSITION_PARAM::di, PROFILE_POSITION_PARAM::ei, PROFILE_POSITION_PARAM::fi, PROFILE_POSITION_PARAM::gi, profile_pos_params, PROFILE_POSITION_PARAM::q, PROFILE_POSITION_PARAM::s_time, PROFILE_POSITION_PARAM::tb_acc, PROFILE_POSITION_PARAM::tb_dec, PROFILE_POSITION_PARAM::tf, PROFILE_POSITION_PARAM::ts, and PROFILE_POSITION_PARAM::vi.
Referenced by ecat_motor_drive(), and set_profile_position().
int quick_stop_position_profile_generate (int steps, int actual_velocity)
Generate Quick Stop Position Profile.
Input
Parameters
step current step of the profile
actual_velocity Output
Returns
corresponding target position at the step input
Definition at line 99 of file profile_position_quick-stop.c.
References pos_params::ci, pos_params::cur_pos_s, pos_param_s, pos_params::q, pos_params::qf, pos_params::t_int, and pos_params::ts.
Referenced by ecat_motor_drive().
int quick_stop_velocity_profile_generate (int step)
Generate Quick Stop Velocity Profile.
Input
Parameters
step current step of the profile
Output
Returns
corresponding target velocity at the step input
Definition at line 77 of file profile_velocity_quick-stop.c.
References QUICK_STOP_VELOCITY_PARAM::a_d, qstop_vel_params, QUICK_STOP_VELOCITY_PARAM::s_time, and QUICK_STOP_VELOCITY_PARAM::u.
Referenced by ecat_motor_drive().
int velocity_profile_generate (int step)
Generate Velocity Profile.
Input
Parameters
step current step of the profile
Output
Returns
corresponding target velocity at the step input
Definition at line 156 of file profile_velocity.c.
References PROFILE_VELOCITY_PARAM::a_d, profile_vel_params, PROFILE_VELOCITY_PARAM::s_time, and PROFILE_VELOCITY_PARAM::u.
Referenced by ecat_motor_drive(), and set_profile_velocity().