sc_sncn_motoctrl_sin: module_qei/src/qei_client.xc File Reference
qei_client.xc File Reference
#include "qei_client.h"
Functions
void init_qei_velocity_params (qei_velocity_par &qei_velocity_params)
Initialize struct for velocity calculation from QEI sensor.
Detailed Description
QEI Sensor Client Functions
Copyright (c) 2014, Synapticon GmbH & XMOS Ltd All rights reserved. Authors: Pavan Kanajar pkana.nosp@m.jar@.nosp@m.synap.nosp@m.tico.nosp@m.n.com & Martin Schwarz mschw.nosp@m.arz@.nosp@m.synap.nosp@m.tico.nosp@m.n.com
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Execution of this software or parts of it exclusively takes place on hardware produced by Synapticon GmbH.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
The views and conclusions contained in the software and documentation are those of the authors and should not be interpreted as representing official policies, either expressed or implied, of the Synapticon GmbH.
Definition in file qei_client.xc.
Function Documentation
void init_qei_velocity_params (qei_velocity_par & qei_velocity_params)
Initialize struct for velocity calculation from QEI sensor.
Input struct is initialised
Definition at line 43 of file qei_client.xc.
References QEI_VELOCITY_PARAM::filter_buffer, QEI_VELOCITY_PARAM::filter_length, QEI_VELOCITY_PARAM::index, init_filter(), QEI_VELOCITY_PARAM::old_difference, and QEI_VELOCITY_PARAM::previous_position.
Referenced by _torque_ctrl(), commutation_sinusoidal_loop(), and qei_test().