sc_sncn_motoctrl_sin: module_blocks/src/util/sine_table_big.h File Reference
sine_table_big.h File Reference
Sine Loopup table declarations.
Functions
int arctg1 (int Real, int Imag)
int sine_third_expanded (int angle)
int sine_table_expanded (int angle)
Variables
short arctg_table []
short sine_third [257]
short sine_table [257]
Detailed Description
Sine Loopup table declarations.
Authors
Martin Schwarz mschw.nosp@m.arz@.nosp@m.synap.nosp@m.tico.nosp@m.n.com, Ludwig Orgler lorgl.nosp@m.er@s.nosp@m.ynapt.nosp@m.icon.nosp@m..com
Definition in file sine_table_big.h.
Function Documentation
int arctg1 (int Real, int Imag)
Definition at line 48 of file arctan.xc.
References arctg_table, and defFactor.
int sine_table_expanded (int angle)
Definition at line 179 of file arctan.xc.
References sine_expanded(), and SINE_TABLE.
Referenced by _torque_ctrl().
int sine_third_expanded (int angle)
Definition at line 174 of file arctan.xc.
References COMMUTATION, and sine_expanded().
Referenced by commutation_sinusoidal_loop().
Variable Documentation
short arctg_table[]
Definition at line 44 of file sine_table_big.c.
Referenced by arctg1().
short sine_table[257]
Definition at line 137 of file sine_table_big.c.
Referenced by sine_expanded().
short sine_third[257]
Definition at line 101 of file sine_table_big.c.
Referenced by sine_expanded().