sc_sncn_motoctrl_sin: test_velocity-ctrl/config/motor/bldc_motor_init.xc File Reference
bldc_motor_init.xc File Reference
#include <bldc_motor_config.h>
#include "refclk.h"
Functions
int __qei_max_counts (int real_counts)
Internal function to calculate QEI position information.
void init_hall_param (hall_par &hall_params)
initialize hall sensor
void init_qei_param (qei_par &qei_params)
initialize QEI sensor
void init_sensor_filter_param (filter_par &sensor_filter_par)
initialize Velocity sensor filter
void init_csv_param (csv_par &csv_params)
initialize cyclic synchronous velocity params
void init_csp_param (csp_par &csp_params)
initialize cyclic synchronous position params
void init_pp_params (pp_par &pp_params)
initialize profile position params
void init_pv_params (pv_par &pv_params)
initialize profile velocity params
void init_pt_params (pt_par &pt_params)
initialize profile torque params
void init_velocity_control_param (ctrl_par &velocity_ctrl_params)
initialize velocity control PID params
void init_position_control_param (ctrl_par &position_ctrl_params)
initialize position control PID params
void init_torque_control_param (ctrl_par &torque_ctrl_params)
initialize torque control PID params
void init_cst_param (cst_par &cst_params)
initialize cyclic synchronous torque params
Function Documentation
int __qei_max_counts (int real_counts)
Internal function to calculate QEI position information.
Input qei counts per rotation
Output
Returns
max position from qei sensor
Definition at line 42 of file qei.c.
Referenced by update_qei_param_ecat().
void init_csp_param (csp_par & csp_params)
initialize cyclic synchronous position params
Parameters
csp_params struct defines cyclic synchronous position params
Definition at line 78 of file bldc_motor_init.xc.
References CYCLIC_SYNCHRONOUS_POSITION_PARAM::base, MAX_ACCELERATION, CYCLIC_SYNCHRONOUS_VELOCITY_PARAM::max_acceleration, CYCLIC_SYNCHRONOUS_POSITION_PARAM::max_following_error, CYCLIC_SYNCHRONOUS_VELOCITY_PARAM::max_motor_speed, MAX_NOMINAL_SPEED, MAX_POSITION_LIMIT, CYCLIC_SYNCHRONOUS_POSITION_PARAM::max_position_limit, MIN_POSITION_LIMIT, CYCLIC_SYNCHRONOUS_POSITION_PARAM::min_position_limit, POLARITY, and CYCLIC_SYNCHRONOUS_VELOCITY_PARAM::polarity.
Referenced by ecat_motor_drive().
void init_cst_param (cst_par & cst_params)
initialize cyclic synchronous torque params
Parameters
cst_params struct defines cyclic synchronous torque params
Definition at line 194 of file bldc_motor_init.xc.
References IFM_RESOLUTION, MAX_NOMINAL_CURRENT, MAX_NOMINAL_SPEED, CYCLIC_SYNCHRONOUS_TORQUE_PARAM::max_torque, MOTOR_TORQUE_CONSTANT, CYCLIC_SYNCHRONOUS_TORQUE_PARAM::motor_torque_constant, CYCLIC_SYNCHRONOUS_TORQUE_PARAM::nominal_current, CYCLIC_SYNCHRONOUS_TORQUE_PARAM::nominal_motor_speed, POLARITY, and CYCLIC_SYNCHRONOUS_TORQUE_PARAM::polarity.
Referenced by ecat_motor_drive(), and profile_torque_test().
void init_csv_param (csv_par & csv_params)
initialize cyclic synchronous velocity params
Parameters
csv_params struct defines cyclic synchronous velocity params
Definition at line 67 of file bldc_motor_init.xc.
References MAX_ACCELERATION, CYCLIC_SYNCHRONOUS_VELOCITY_PARAM::max_acceleration, CYCLIC_SYNCHRONOUS_VELOCITY_PARAM::max_motor_speed, MAX_NOMINAL_SPEED, POLARITY, and CYCLIC_SYNCHRONOUS_VELOCITY_PARAM::polarity.
Referenced by ecat_motor_drive().
void init_hall_param (hall_par & hall_params)
initialize hall sensor
Parameters
hall_params struct defines the pole-pairs and gear ratio
Definition at line 44 of file bldc_motor_init.xc.
References GEAR_RATIO, S_Hall::gear_ratio, POLE_PAIRS, and S_Hall::pole_pairs.
Referenced by ecat_motor_drive(), hall_test(), and main().
void init_position_control_param (ctrl_par & position_ctrl_params)
initialize position control PID params
Parameters
position_ctrl_params struct defines position control PID params
Definition at line 142 of file bldc_motor_init.xc.
References S_Control::Control_limit, S_Control::Integral_limit, S_Control::Kd_d, S_Control::Kd_n, S_Control::Ki_d, S_Control::Ki_n, S_Control::Kp_d, S_Control::Kp_n, S_Control::Loop_time, MSEC_STD, POSITION_Kd_DENOMINATOR, POSITION_Kd_NUMERATOR, POSITION_Ki_DENOMINATOR, POSITION_Ki_NUMERATOR, POSITION_Kp_DENOMINATOR, and POSITION_Kp_NUMERATOR.
Referenced by main().
void init_pp_params (pp_par & pp_params)
initialize profile position params
Parameters
pp_params struct defines profileposition params
Definition at line 92 of file bldc_motor_init.xc.
References PROFILE_POSITION_PARAM::base, PROFILE_POSITION_PARAM::max_acceleration, MAX_ACCELERATION, MAX_POSITION_LIMIT, MAX_PROFILE_VELOCITY, PROFILE_VELOCITY_PARAM::max_profile_velocity, MIN_POSITION_LIMIT, POLARITY, PROFILE_VELOCITY_PARAM::polarity, PROFILE_ACCELERATION, PROFILE_VELOCITY_PARAM::profile_acceleration, PROFILE_DECELERATION, PROFILE_VELOCITY_PARAM::profile_deceleration, PROFILE_VELOCITY, PROFILE_POSITION_PARAM::profile_velocity, QUICK_STOP_DECELERATION, PROFILE_VELOCITY_PARAM::quick_stop_deceleration, PROFILE_POSITION_PARAM::software_position_limit_max, and PROFILE_POSITION_PARAM::software_position_limit_min.
Referenced by ecat_motor_drive().
void init_pt_params (pt_par & pt_params)
initialize profile torque params
Parameters
pt_params struct defines profile torque params
Definition at line 116 of file bldc_motor_init.xc.
References POLARITY, PROFILE_TORQUE_PARAM::polarity, PROFILE_TORQUE_PARAM::profile_slope, and PROFILE_TORQUE_SLOPE.
Referenced by ecat_motor_drive().
void init_pv_params (pv_par & pv_params)
initialize profile velocity params
Parameters
pv_params struct defines profile velocity params
Definition at line 106 of file bldc_motor_init.xc.
References MAX_PROFILE_VELOCITY, PROFILE_VELOCITY_PARAM::max_profile_velocity, POLARITY, PROFILE_VELOCITY_PARAM::polarity, PROFILE_ACCELERATION, PROFILE_VELOCITY_PARAM::profile_acceleration, PROFILE_DECELERATION, PROFILE_VELOCITY_PARAM::profile_deceleration, QUICK_STOP_DECELERATION, and PROFILE_VELOCITY_PARAM::quick_stop_deceleration.
Referenced by ecat_motor_drive().
void init_qei_param (qei_par & qei_params)
initialize QEI sensor
Parameters
qei_params struct defines the resolution for quadrature encoder (QEI), gear-ratio, poles, encoder type
Definition at line 51 of file bldc_motor_init.xc.
References __qei_max_counts(), ENCODER_RESOLUTION, GEAR_RATIO, S_QEI::gear_ratio, S_QEI::index, S_QEI::max_count, POLE_PAIRS, S_QEI::poles, QEI_SENSOR_TYPE, and S_QEI::real_counts.
Referenced by ecat_motor_drive(), main(), and qei_test().
void init_sensor_filter_param (filter_par & sensor_filter_par)
initialize Velocity sensor filter
Parameters
sensor_filter_par struct defines the velocity filter params
Definition at line 61 of file bldc_motor_init.xc.
References S_Filter_length::filter_length, and VELOCITY_FILTER_SIZE.
Referenced by main().
void init_torque_control_param (ctrl_par & torque_ctrl_params)
initialize torque control PID params
Parameters
torque_ctrl_params struct defines torque control PID params
Definition at line 169 of file bldc_motor_init.xc.
References S_Control::Control_limit, S_Control::Integral_limit, S_Control::Kd_d, S_Control::Kd_n, S_Control::Ki_d, S_Control::Ki_n, S_Control::Kp_d, S_Control::Kp_n, S_Control::Loop_time, MSEC_STD, TORQUE_Kd_DENOMINATOR, TORQUE_Kd_NUMERATOR, TORQUE_Ki_DENOMINATOR, TORQUE_Ki_NUMERATOR, TORQUE_Kp_DENOMINATOR, and TORQUE_Kp_NUMERATOR.
Referenced by main().
void init_velocity_control_param (ctrl_par & velocity_ctrl_params)
initialize velocity control PID params
Parameters
velocity_ctrl_params struct defines velocity control PID params
Definition at line 122 of file bldc_motor_init.xc.
References S_Control::Control_limit, S_Control::Integral_limit, S_Control::Kd_d, S_Control::Kd_n, S_Control::Ki_d, S_Control::Ki_n, S_Control::Kp_d, S_Control::Kp_n, S_Control::Loop_time, MSEC_STD, VELOCITY_Kd_DENOMINATOR, VELOCITY_Kd_NUMERATOR, VELOCITY_Ki_DENOMINATOR, VELOCITY_Ki_NUMERATOR, VELOCITY_Kp_DENOMINATOR, and VELOCITY_Kp_NUMERATOR.
Referenced by main().