sc_sncn_motoctrl_sin: test_position-ctrl/src/test_position-ctrl.xc File Reference
test_position-ctrl.xc File Reference
Main project file Test illustrates usage of profile position control.
#include <xs1.h>
#include <platform.h>
#include <print.h>
#include <stdio.h>
#include <stdint.h>
#include <ioports.h>
#include <hall_server.h>
#include <pwm_service_inv.h>
#include <comm_loop_server.h>
#include <refclk.h>
#include <xscope.h>
#include <qei_server.h>
#include <bldc_motor_config.h>
#include <profile.h>
#include <position_ctrl_server.h>
#include <drive_config.h>
#include <profile_control.h>
#include <internal_config.h>
#include <flash_somanet.h>
Macros
#define COM_CORE 0
#define IFM_CORE 3
Functions
void xscope_initialise_1 ()
void position_profile_test (chanend c_position_ctrl)
int main (void)
Variables
on stdcore [IFM_CORE]
Detailed Description
Main project file Test illustrates usage of profile position control.
Copyright (c) 2014, Synapticon GmbH All rights reserved. Author: Pavan Kanajar pkana.nosp@m.jar@.nosp@m.synap.nosp@m.tico.nosp@m.n.com & Martin Schwarz mschw.nosp@m.arz@.nosp@m.synap.nosp@m.tico.nosp@m.n.com
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Execution of this software or parts of it exclusively takes place on hardware produced by Synapticon GmbH.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
The views and conclusions contained in the software and documentation are those of the authors and should not be interpreted as representing official policies, either expressed or implied, of the Synapticon GmbH.
Definition in file test_position-ctrl.xc.
Macro Definition Documentation
#define COM_CORE 0
Definition at line 63 of file test_position-ctrl.xc.
Referenced by main().
#define IFM_CORE 3
Definition at line 64 of file test_position-ctrl.xc.
Referenced by main().
Function Documentation
int main (void)
Definition at line 100 of file test_position-ctrl.xc.
References COM_CORE, commutation_sinusoidal(), IFM_CORE, init_commutation_param(), init_hall_param(), init_position_control_param(), init_qei_param(), MAX_NOMINAL_SPEED, position_control(), position_profile_test(), run_hall(), run_qei(), run_watchdog(), SENSOR_USED, and stdcore.
void position_profile_test (chanend c_position_ctrl)
Definition at line 81 of file test_position-ctrl.xc.
References GEAR_RATIO, init_position_profile_limits(), MAX_ACCELERATION, MAX_POSITION_LIMIT, MAX_PROFILE_VELOCITY, MIN_POSITION_LIMIT, set_profile_position(), and xscope_initialise_1().
Referenced by main().
void xscope_initialise_1 ()
Definition at line 70 of file test_position-ctrl.xc.
Referenced by position_profile_test().
Variable Documentation
on stdcore[IFM_CORE]
Definition at line 66 of file test_position-ctrl.xc.
Referenced by main().