sc_sncn_motoctrl_sin: module_ctrl_loops/torque/torque_ctrl_server.h File Reference
torque_ctrl_server.h File Reference
#include "comm_loop_client.h"
#include <bldc_motor_config.h>
#include <internal_config.h>
Functions
void torque_control (ctrl_par &torque_ctrl_params, hall_par &hall_params, qei_par &qei_params, int sensor_used, chanend c_adc, chanend c_commutation, chanend c_hall, chanend c_qei, chanend c_torque_ctrl)
Torque Control Loop.
Detailed Description
Torque Control Loop Server
Copyright (c) 2014, Synapticon GmbH All rights reserved. Author: Pavan Kanajar pkana.nosp@m.jar@.nosp@m.synap.nosp@m.tico.nosp@m.n.com
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Execution of this software or parts of it exclusively takes place on hardware produced by Synapticon GmbH.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
The views and conclusions contained in the software and documentation are those of the authors and should not be interpreted as representing official policies, either expressed or implied, of the Synapticon GmbH.
Definition in file torque_ctrl_server.h.
Function Documentation
void torque_control (ctrl_par & torque_ctrl_params, hall_par & hall_params, qei_par & qei_params, int sensor_used, chanend c_adc, chanend c_commutation, chanend c_hall, chanend c_qei, chanend c_torque_ctrl)
Torque Control Loop.
Input
Parameters
torque_ctrl_params struct defines the torque control parameters
hall_params struct defines the poles for hall sensor and gear-ratio
qei_params struct defines the resolution for qei sensor and gear-ratio
sensor_used specify the sensor to use via HALL/QEI defines
Input Channel c_adc channel to receive to torque information from current sensor c_hall channel to receive position information from hall c_qei channel to receive position information from qei c_torque channel to receive/send torque control information
Output Channel c_commutation channel to send motor voltage input value
Definition at line 587 of file torque_ctrl_server.xc.
References _torque_ctrl(), and current_filter().
Referenced by main().