sc_sncn_motoctrl_sin: module_ctrl_loops/torque/torque_ctrl_client.h File Reference
torque_ctrl_client.h File Reference
#include <bldc_motor_config.h>
#include <internal_config.h>
Functions
int init_torque_control (chanend c_torque_ctrl)
Initialise Torque Control Loop.
int check_torque_ctrl_state (chanend c_torque_ctrl)
Checks Torque Control Loop Status.
int torque_limit (int torque, int max_torque_limit)
Torque Limiter.
int get_torque (cst_par &cst_params, chanend c_torque_ctrl)
Get actual torque from Torque Control Loop.
void set_torque (int torque, cst_par &cst_params, chanend c_torque_ctrl)
Set new target torque for Torque Control Loop.
void set_torque_ctrl_param (ctrl_par &torque_ctrl_params, chanend c_torque_ctrl)
Set Torque Control PID Parameters.
void set_torque_ctrl_hall_param (hall_par &hall_params, chanend c_torque_ctrl)
Set hall sensor parameters for Torque Control.
void set_torque_ctrl_qei_param (qei_par &qei_params, chanend c_torque_ctrl)
Set QEI sensor parameters for Torque Control.
void set_torque_sensor (int sensor_used, chanend c_torque_ctrl)
Sets the sensor used for Torque Control.
void enable_torque_ctrl (chanend c_torque_ctrl)
Enables Torque Control mode operation.
void shutdown_torque_ctrl (chanend c_torque_ctrl)
Shutdown Torque Control mode operation.
void set_torque_cst (cst_par &cst_params, int target_torque, int torque_offset, chanend c_torque_ctrl)
Set new target torque for torque control (advanced function)
Detailed Description
Torque Control Loop Client functions
Copyright (c) 2014, Synapticon GmbH All rights reserved. Author: Pavan Kanajar pkana.nosp@m.jar@.nosp@m.synap.nosp@m.tico.nosp@m.n.com
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Execution of this software or parts of it exclusively takes place on hardware produced by Synapticon GmbH.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
The views and conclusions contained in the software and documentation are those of the authors and should not be interpreted as representing official policies, either expressed or implied, of the Synapticon GmbH.
Definition in file torque_ctrl_client.h.
Function Documentation
int check_torque_ctrl_state (chanend c_torque_ctrl)
Checks Torque Control Loop Status.
Input Channel c_torque_ctrl channel to get state of control loop
Output
Returns
state of the control loop : 1 - active, 0 - inactive
Definition at line 169 of file torque_ctrl_client.xc.
References TORQUE_CTRL_READ, TORQUE_CTRL_STATUS, and TORQUE_CTRL_WRITE.
Referenced by ecat_motor_drive(), and init_torque_control().
void enable_torque_ctrl (chanend c_torque_ctrl)
Enables Torque Control mode operation.
c_torque_ctrl channel to signal enable torque control
Definition at line 157 of file torque_ctrl_client.xc.
References ENABLE_TORQUE_CTRL, and TORQUE_CTRL_WRITE.
Referenced by init_torque_control().
int get_torque (cst_par & cst_params, chanend c_torque_ctrl)
Get actual torque from Torque Control Loop.
Output Channel c_torque channel to receive actual torque
Output
Returns
actual torque from torque control in range [0 - mNm * Current Resolution]
Definition at line 71 of file torque_ctrl_client.xc.
References GET_TORQUE_TOKEN, TORQUE_CTRL_READ, and TORQUE_CTRL_WRITE.
Referenced by ecat_motor_drive(), and set_profile_torque().
int init_torque_control (chanend c_torque_ctrl)
Initialise Torque Control Loop.
Input Channel c_torque_ctrl channel to signal initialisation
Definition at line 49 of file torque_ctrl_client.xc.
References check_torque_ctrl_state(), enable_torque_ctrl(), INIT, and INIT_BUSY.
Referenced by ecat_motor_drive(), and set_profile_torque().
void set_torque (int torque, cst_par & cst_params, chanend c_torque_ctrl)
Set new target torque for Torque Control Loop.
Input Channel c_torque channel to signal new target torque
Input
Parameters
torque is the new target torque range [0 - mNm * Current Resolution]
Definition at line 79 of file torque_ctrl_client.xc.
References SET_TORQUE_TOKEN, and TORQUE_CTRL_WRITE.
Referenced by ecat_motor_drive(), set_profile_torque(), and set_torque_cst().
void set_torque_cst (cst_par & cst_params, int target_torque, int torque_offset, chanend c_torque_ctrl)
Set new target torque for torque control (advanced function)
Input Channel c_torque_ctrl channel to signal new target torque
Input
Parameters
cst_param struct defines the motor parameters and torque limits
target_torque is the new target torque
torque_offset defines offset in torque
Definition at line 117 of file torque_ctrl_client.xc.
References CYCLIC_SYNCHRONOUS_TORQUE_PARAM::max_torque, CYCLIC_SYNCHRONOUS_TORQUE_PARAM::polarity, set_torque(), and torque_limit().
Referenced by ecat_motor_drive().
void set_torque_ctrl_hall_param (hall_par & hall_params, chanend c_torque_ctrl)
Set hall sensor parameters for Torque Control.
Parameters
hall_params struct defines the pole-pairs and gear ratio
Definition at line 135 of file torque_ctrl_client.xc.
References S_Hall::gear_ratio, S_Hall::pole_pairs, SET_TORQUE_CTRL_HALL, and TORQUE_CTRL_WRITE.
Referenced by ecat_motor_drive().
void set_torque_ctrl_param (ctrl_par & torque_ctrl_params, chanend c_torque_ctrl)
Set Torque Control PID Parameters.
Input
Parameters
torque_ctrl_params struct defines the torque control PID parameters
Definition at line 123 of file torque_ctrl_client.xc.
References S_Control::Integral_limit, S_Control::Kd_d, S_Control::Kd_n, S_Control::Ki_d, S_Control::Ki_n, S_Control::Kp_d, S_Control::Kp_n, SET_CTRL_PARAMETER, and TORQUE_CTRL_WRITE.
Referenced by ecat_motor_drive().
void set_torque_ctrl_qei_param (qei_par & qei_params, chanend c_torque_ctrl)
Set QEI sensor parameters for Torque Control.
Parameters
qei_params struct defines the quadrature encoder (QEI) resolution, sensor type and gear-ratio used for the motor
Definition at line 142 of file torque_ctrl_client.xc.
References S_QEI::gear_ratio, S_QEI::index, S_QEI::max_count, S_QEI::poles, S_QEI::real_counts, SET_TORQUE_CTRL_QEI, and TORQUE_CTRL_WRITE.
Referenced by ecat_motor_drive().
void set_torque_sensor (int sensor_used, chanend c_torque_ctrl)
Sets the sensor used for Torque Control.
Parameters
sensor_used defines the sensor to be used (HALL/QEI) for Torque Control
Definition at line 151 of file torque_ctrl_client.xc.
References SENSOR_SELECT, and TORQUE_CTRL_WRITE.
Referenced by ecat_motor_drive().
void shutdown_torque_ctrl (chanend c_torque_ctrl)
Shutdown Torque Control mode operation.
c_torque_ctrl channel to signal shutdown of torque control
Definition at line 163 of file torque_ctrl_client.xc.
References SHUTDOWN_TORQUE_CTRL, and TORQUE_CTRL_WRITE.
Referenced by ecat_motor_drive().
int torque_limit (int torque, int max_torque_limit)
Torque Limiter.
Input
Parameters
torque is the input torque to be limited in range
max_torque_limit is the max torque that can be reached
Output
Returns
torque in the range [-max_torque_limit to max_torque_limit] (mNm * Current resolution)
Definition at line 101 of file torque_ctrl_client.xc.
Referenced by set_torque_cst().