sc_sncn_motoctrl_sin: module_ctrl_loops/torque/torque_ctrl_server.xc File Reference
torque_ctrl_server.xc File Reference
#include "torque_ctrl_server.h"
#include <refclk.h>
#include <xscope.h>
#include <print.h>
#include <drive_config.h>
#include <internal_config.h>
#include <bldc_motor_config.h>
#include "adc_client_ad7949.h"
#include "qei_client.h"
#include "hall_client.h"
Macros
#define FILTER_LENGTH_ADC 80
#define FILTER_LENGTH_TORQUE 80
Functions
int root_function (int arg)
void init_buffer (int buffer[], int length)
void current_filter (chanend c_adc, chanend c_current, chanend c_speed)
void _torque_ctrl (ctrl_par &torque_ctrl_params, hall_par &hall_params, qei_par &qei_params, int sensor_used, chanend c_current, chanend c_speed, chanend c_commutation, chanend c_hall, chanend c_qei, chanend c_torque_ctrl)
void torque_control (ctrl_par &torque_ctrl_params, hall_par &hall_params, qei_par &qei_params, int sensor_used, chanend c_adc, chanend c_commutation, chanend c_hall, chanend c_qei, chanend c_torque_ctrl)
Torque Control Loop.
Detailed Description
Torque Control Loop Server
Copyright (c) 2014, Synapticon GmbH All rights reserved. Author: Pavan Kanajar pkana.nosp@m.jar@.nosp@m.synap.nosp@m.tico.nosp@m.n.com
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Execution of this software or parts of it exclusively takes place on hardware produced by Synapticon GmbH.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
The views and conclusions contained in the software and documentation are those of the authors and should not be interpreted as representing official policies, either expressed or implied, of the Synapticon GmbH.
Definition in file torque_ctrl_server.xc.
Macro Definition Documentation
#define FILTER_LENGTH_ADC 80
Referenced by current_filter().
#define FILTER_LENGTH_TORQUE 80
Referenced by _torque_ctrl().
Function Documentation
void _torque_ctrl (ctrl_par & torque_ctrl_params, hall_par & hall_params, qei_par & qei_params, int sensor_used, chanend c_current, chanend c_speed, chanend c_commutation, chanend c_hall, chanend c_qei, chanend c_torque_ctrl)
Definition at line 190 of file torque_ctrl_server.xc.
References __check_commutation_init(), CHECK_BUSY, S_Control::Control_limit, ENABLE_TORQUE_CTRL, FILTER_LENGTH_TORQUE, S_QEI::gear_ratio, S_Hall::gear_ratio, get_hall_position(), get_hall_velocity(), get_qei_velocity(), GET_TORQUE_TOKEN, HALL, S_QEI::index, INIT, init_buffer(), INIT_BUSY, init_qei_velocity_params(), init_state(), S_Control::Integral_limit, S_Control::Kd_d, S_Control::Kd_n, S_Control::Ki_d, S_Control::Ki_n, S_Control::Kp_d, S_Control::Kp_n, S_QEI::max_count, MSEC_STD, S_Hall::pole_pairs, S_QEI::poles, QEI, S_QEI::real_counts, root_function(), SENSOR_SELECT, SET, set_commutation_sinusoidal(), SET_CTRL_PARAMETER, SET_TORQUE_CTRL_HALL, SET_TORQUE_CTRL_QEI, SET_TORQUE_TOKEN, SHUTDOWN_TORQUE_CTRL, sine_table_expanded(), TORQUE_CTRL_READ, TORQUE_CTRL_STATUS, TORQUE_CTRL_WRITE, and UNSET.
Referenced by torque_control().
void current_filter (chanend c_adc, chanend c_current, chanend c_speed)
Definition at line 67 of file torque_ctrl_server.xc.
References do_adc_calibration_ad7949(), FILTER_LENGTH_ADC, and init_buffer().
Referenced by torque_control().
void init_buffer (int buffer[], int length)
Definition at line 57 of file torque_ctrl_server.xc.
Referenced by _torque_ctrl(), and current_filter().
int root_function (int arg)
Definition at line 65 of file precision.c.
References result_tor.
Referenced by _torque_ctrl().
void torque_control (ctrl_par & torque_ctrl_params, hall_par & hall_params, qei_par & qei_params, int sensor_used, chanend c_adc, chanend c_commutation, chanend c_hall, chanend c_qei, chanend c_torque_ctrl)
Torque Control Loop.
Input
Parameters
torque_ctrl_params struct defines the torque control parameters
hall_params struct defines the poles for hall sensor and gear-ratio
qei_params struct defines the resolution for qei sensor and gear-ratio
sensor_used specify the sensor to use via HALL/QEI defines
Input Channel c_adc channel to receive to torque information from current sensor c_hall channel to receive position information from hall c_qei channel to receive position information from qei c_torque channel to receive/send torque control information
Output Channel c_commutation channel to send motor voltage input value
Definition at line 587 of file torque_ctrl_server.xc.
References _torque_ctrl(), and current_filter().
Referenced by main().