sc_sncn_motoctrl_sin: module_ctrl_loops/velocity/velocity_ctrl_client.h File Reference
velocity_ctrl_client.h File Reference
#include <bldc_motor_config.h>
#include <internal_config.h>
Functions
int init_velocity_control (chanend c_velocity_ctrl)
Initialise Velocity Control Loop.
int check_velocity_ctrl_state (chanend c_velocity_ctrl)
Checks Velocity Control Loop Status.
int max_speed_limit (int velocity, int max_speed)
Velocity Limiter.
void set_velocity (int target_velocity, chanend c_velocity_ctrl)
Set new target velocity for Velocity Control Loop.
int get_velocity (chanend c_velocity_ctrl)
Get actual velocity from Velocity Control Loop.
void set_velocity_ctrl_param (ctrl_par &velocity_ctrl_params, chanend c_velocity_ctrl)
Set Velocity Control PID Parameters.
void set_velocity_ctrl_hall_param (hall_par &hall_params, chanend c_velocity_ctrl)
Set hall sensor parameters for Velocity Control.
void set_velocity_ctrl_qei_param (qei_par &qei_params, chanend c_velocity_ctrl)
Set QEI sensor for Velocity Control.
void set_velocity_sensor (int sensor_used, chanend c_velocity_ctrl)
Sets the sensor used for Velocity Control.
void enable_velocity_ctrl (chanend c_velocity_ctrl)
Enables Velocity Control mode operation.
void shutdown_velocity_ctrl (chanend c_velocity_ctrl)
Shutdown Velocity Control mode operation.
void set_velocity_csv (csv_par &csv_params, int target_velocity, int velocity_offset, int torque_offset, chanend c_velocity_ctrl)
Set new target velocity for velocity control (advanced function)
Detailed Description
Velocity Control Loop Client functions
Copyright (c) 2014, Synapticon GmbH All rights reserved. Author: Pavan Kanajar pkana.nosp@m.jar@.nosp@m.synap.nosp@m.tico.nosp@m.n.com
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Execution of this software or parts of it exclusively takes place on hardware produced by Synapticon GmbH.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
The views and conclusions contained in the software and documentation are those of the authors and should not be interpreted as representing official policies, either expressed or implied, of the Synapticon GmbH.
Definition in file velocity_ctrl_client.h.
Function Documentation
int check_velocity_ctrl_state (chanend c_velocity_ctrl)
Checks Velocity Control Loop Status.
Input Channel c_velocity_ctrl channel to get state of control loop
Output
Returns
state of the control loop : 1 - active, 0 - inactive
Definition at line 156 of file velocity_ctrl_client.xc.
References VELOCITY_CTRL_READ, VELOCITY_CTRL_STATUS, and VELOCITY_CTRL_WRITE.
Referenced by ecat_motor_drive(), and init_velocity_control().
void enable_velocity_ctrl (chanend c_velocity_ctrl)
Enables Velocity Control mode operation.
c_velocity_ctrl channel to signal enable velocity control
Definition at line 144 of file velocity_ctrl_client.xc.
References ENABLE_VELOCITY_CTRL, and VELOCITY_CTRL_WRITE.
Referenced by init_velocity_control().
int get_velocity (chanend c_velocity_ctrl)
Get actual velocity from Velocity Control Loop.
Output Channel c_velocity_ctrl channel to receive actual velocity
Output
Returns
actual velocity from velocity control (rpm)
Definition at line 77 of file velocity_ctrl_client.xc.
References GET_VELOCITY_TOKEN, VELOCITY_CTRL_READ, and VELOCITY_CTRL_WRITE.
Referenced by ecat_motor_drive(), and set_profile_velocity().
int init_velocity_control (chanend c_velocity_ctrl)
Initialise Velocity Control Loop.
Input Channel c_velocity_ctrl channel to signal initialisation
Definition at line 49 of file velocity_ctrl_client.xc.
References check_velocity_ctrl_state(), enable_velocity_ctrl(), INIT, and INIT_BUSY.
Referenced by ecat_motor_drive(), and set_profile_velocity().
int max_speed_limit (int velocity, int max_speed)
Velocity Limiter.
Input
Parameters
velocity is the input velocity to be limited in range
max_speed is the max speed that can be reached
Output
Returns
velocity in the range [-max_speed to max_speed] (rpm)
Definition at line 84 of file velocity_ctrl_client.xc.
Referenced by ecat_motor_drive(), and set_velocity_csv().
void set_velocity (int target_velocity, chanend c_velocity_ctrl)
Set new target velocity for Velocity Control Loop.
Input Channel c_velocity_ctrl channel to signal new target velocity
Input
Parameters
target_velocity is the new target velocity (rpm)
Definition at line 72 of file velocity_ctrl_client.xc.
References SET_VELOCITY_TOKEN, and VELOCITY_CTRL_WRITE.
Referenced by ecat_motor_drive(), set_profile_velocity(), and set_velocity_csv().
void set_velocity_csv (csv_par & csv_params, int target_velocity, int velocity_offset, int torque_offset, chanend c_velocity_ctrl)
Set new target velocity for velocity control (advanced function)
Input Channel c_velocity_ctrl channel to signal new target velocity input
Input
Parameters
csv_param struct defines the motor parameters and velocity limits
target_velocity is the new target velocity
velocity_offset defines offset in velocity
torque_offset defines offset in torque
Definition at line 97 of file velocity_ctrl_client.xc.
References CYCLIC_SYNCHRONOUS_VELOCITY_PARAM::max_motor_speed, max_speed_limit(), CYCLIC_SYNCHRONOUS_VELOCITY_PARAM::polarity, and set_velocity().
Referenced by ecat_motor_drive().
void set_velocity_ctrl_hall_param (hall_par & hall_params, chanend c_velocity_ctrl)
Set hall sensor parameters for Velocity Control.
Input
Parameters
hall_params struct defines the pole-pairs and gear ratio
Definition at line 115 of file velocity_ctrl_client.xc.
References S_Hall::gear_ratio, S_Hall::pole_pairs, SET_VELOCITY_CTRL_HALL, and VELOCITY_CTRL_WRITE.
Referenced by ecat_motor_drive().
void set_velocity_ctrl_param (ctrl_par & velocity_ctrl_params, chanend c_velocity_ctrl)
Set Velocity Control PID Parameters.
Input
Parameters
velocity_ctrl_params struct defines the velocity control PID parameters
Definition at line 103 of file velocity_ctrl_client.xc.
References S_Control::Integral_limit, S_Control::Kd_d, S_Control::Kd_n, S_Control::Ki_d, S_Control::Ki_n, S_Control::Kp_d, S_Control::Kp_n, SET_CTRL_PARAMETER, and VELOCITY_CTRL_WRITE.
Referenced by ecat_motor_drive().
void set_velocity_ctrl_qei_param (qei_par & qei_params, chanend c_velocity_ctrl)
Set QEI sensor for Velocity Control.
Input
Parameters
qei_params struct defines the quadrature encoder (QEI) resolution, sensor type and gear-ratio used for the motor
Definition at line 122 of file velocity_ctrl_client.xc.
References S_QEI::gear_ratio, S_QEI::index, S_QEI::max_count, S_QEI::poles, S_QEI::real_counts, SET_VELOCITY_CTRL_QEI, and VELOCITY_CTRL_WRITE.
Referenced by ecat_motor_drive().
void set_velocity_sensor (int sensor_used, chanend c_velocity_ctrl)
Sets the sensor used for Velocity Control.
Input
Parameters
sensor_used defines the sensor to be used (HALL/QEI) for Velocity Control
Definition at line 132 of file velocity_ctrl_client.xc.
References SENSOR_SELECT, and VELOCITY_CTRL_WRITE.
Referenced by ecat_motor_drive().
void shutdown_velocity_ctrl (chanend c_velocity_ctrl)
Shutdown Velocity Control mode operation.
c_velocity_ctrl channel to signal shutdown of velocity control
Definition at line 150 of file velocity_ctrl_client.xc.
References SHUTDOWN_VELOCITY_CTRL, and VELOCITY_CTRL_WRITE.
Referenced by ecat_motor_drive().