all: html

SPHINX_PROJECT_NAME = SOMANET Standalone Profile Position Control Demo 
VERSION = 1.0
SOURCE_INCLUDE_DIRS = ../../app_demo_bldc_position
XDOC_DIR ?= ../../../xdoc
include $(XDOC_DIR)/Makefile.inc
