all: html

SPHINX_PROJECT_NAME = SOMANET Motor Control Configuration and Tuning Guide
VERSION = 1.0
SOURCE_INCLUDE_DIRS = ../../sc_sncn_motorcontrol
XDOC_DIR ?= ../../../xdoc
include $(XDOC_DIR)/Makefile.inc
