all: html

SPHINX_PROJECT_NAME = SOMANET Standalone Profile Torque Control Demo
VERSION = 1.0
SOURCE_INCLUDE_DIRS = ../../app_demo_bldc_torque
XDOC_DIR ?= ../../../xdoc
include $(XDOC_DIR)/Makefile.inc
