#pragma once

enum { PCTRL_CMD_SET_HALL,
       PCTRL_CMD_SET_QEI,
       PCTRL_CMD_GET_POSITION,
       PCTRL_CMD_SET_POSITION,
       PCTRL_CMD_SET_PARAMS,
       PCTRL_CMD_ENABLE,
       PCTRL_CMD_SHUTDOWN,
       PCTRL_CMD_GET_STATUS };

