#pragma once

enum { VCTRL_CMD_SET_HALL,
       VCTRL_CMD_SET_QEI,
       VCTRL_CMD_GET_VELOCITY,
       VCTRL_CMD_SET_VELOCITY,
       VCTRL_CMD_ENABLE,
       VCTRL_CMD_SHUTDOWN,
       VCTRL_CMD_GET_STATUS };

